cmd/connect.go
The connect command didnt have support for --sshserver This PR adds support for that
=> Support for local SSH server in connect

internal/client/client.go
=> New Success and Fail page

cmd/connect.go, cmd/root.go, cmd/socket.go
Deprecating cloud auth in favor of policies
Printing warning if no policies have been applied
Printing Name
=> Fixing cloud auth

cmd/policy.go, cmd/root.go, go.mod, go.sum
Color in output
and validate if json is valid on policy create
=> color and json validation

cmd/connect.go, cmd/policy.go, cmd/root.go, cmd/socket.go, internal/api/models/policy.go
this is so we properly print org wide policies in cli
=> Org wide polices

internal/client/client.go
we load up the client token to env.variable ```export BORDER0_CLIENT_TOKEN=$(cat ~/.border0/client_token)```
then, with all token files removed ```:~$ rm -fr .border0```
we can call the client ssh connect function using env.variable supplied token
```
:~$ border0 client ssh -l root
? choose a host: border0-bastion-the-greg-rnd.border0.io []
Connecting to Server: border0-bastion-the-greg-rnd.border0.io:19386 as root 
root@411470c8b7dd:~# ps xaf
PID TTY      STAT   TIME COMMAND
1 ?        Ssl    0:01 /code/border0 connect --type ssh --name border0-bastion --sshserver
156 pts/0    Ss     0:00 -bash
161 pts/0    R+     0:00  \_ ps xaf
root@411470c8b7dd:~# 
```
=> expiry check for client token supplied as os variable

cmd/login.go
increasing the retry frequency, so log in flow is smoother
=> Faster login

internal/http/handler.go
- Uses constants in the `net/http` package e.g.
- `200`, `401`, `404` --> `http.StatusOK`, `http.StatusUnauthorized`, `http.StatusNotFound`
- `GET`, `POST` --> `http.MethodGet`, `http.MethodPost`
- Catches and handles a few uncaught errors (notably: http req object creations)
- Consistent use of `http.Post` and `http.Get` when the header need not be modified and `http.NewRequest` when the header needs to be modified (e.g. to set creds, etc)
=> Minor readability improvements to internal/http package

cmd/policy.go
- currently, `policy ls` command is displaying only org-wide policies, this will fix that and return all policies.
- creating some policies and checking if all of them returned by the `policy ls` command
=> fix: show all policies in the list policy command

cmd/account.go, cmd/client.go, cmd/tunnel.go, cmd/version.go, internal/client/mysqlworkbench/connection.go, main.go, mocks/api_mock.go, mocks/discover_mock.go
Format go code (gofmt -s -w)
None of the above -- it's a non-functional change.
No need -- non functional change.
=> Format go code (gofmt -s -w)

cmd/account.go, cmd/organization.go, cmd/root.go, cmd/socket.go, internal/api/models/domain.go, internal/api/models/organization.go, internal/api/models/socket.go
This PR adds support to the border0 cli for organization custom domains.
It also includes some minor changes to show the organization subdomain.
This has been tested with a local build.
=> feat: organazition custom domain support

.github/workflows/build_and_release.yml
Update build and release github actions workflow to use node16
=> actions: update to node16

cmd/idp/cmd_idp_add_googleworkspace.go, cmd/idp/cmd_idp_add_oidc.go, cmd/idp/cmd_idp_add_oktaworkforce.go, cmd/idp/cmd_idp_add_saml.go, cmd/idp/cmd_idp_disable.go, cmd/idp/cmd_idp_enable.go, cmd/idp/cmd_idp_list.go, cmd/idp/cmd_idp_remove.go, cmd/idp/cmd_idp_show.go, cmd/idp/cmd_idp_update_googleworkspace.go, cmd/idp/cmd_idp_update_oidc.go, cmd/idp/cmd_idp_update_oktaworkforce.go, cmd/idp/cmd_idp_update_saml.go, cmd/idp/common.go, cmd/idp/root_idp.go, cmd/idp/root_idp_add.go, cmd/idp/root_idp_update.go, cmd/organization.go, internal/http/handler.go, internal/util/fail_pretty.go
Introduces support for the API's customer identity provider endpoints
Tested against the latest production API
[ME-917]: https://mysocket.atlassian.net/browse/ME-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-917] Organization Identity Provider Cmd Tree

cmd/account.go, cmd/completion.go, cmd/policy.go, cmd/root.go, cmd/socket.go, cmd/version.go, internal/api/models/socket.go
support for upstream client certificates and CA.
Replace deprecated ioutil functions.
Fixes #ME-1007
=> feat(ME-1007): support for upstream client certificates and CA

cmd/client.go, cmd/client/db/dbeaver.go, cmd/client/db/pgcli.go, cmd/client/db/psql.go, internal/api/models/client_resource.go, internal/api/models/socket.go, internal/connector/config/config.go, internal/connector/config/config_test.go, internal/connector/core/core.go, internal/connector/discover/docker.go, internal/connector/discover/ec2.go, internal/connector/discover/k8.go, internal/connector/discover/networkscan.go, internal/connector/discover/static_sockets.go
Removing the private socket code, we decided to not work more with private sockets.
=> [ME-1013] Remove private sockets

internal/ssh/connect.go
- we are closing the ssh connection too earlier which is causing problems that connector thinks it's disconnected but it isn't, for now we will only close the connection when the all retries exhausted
reproducing: 
- simulating an timeout with tunnel server with a rule in firewall
=> fix: [ME-1079 ] connector retry loop

cmd/organization.go, cmd/root.go, internal/api/models/notification.go
Support for notifications in the CLI
Fixes # ME-987
=> feat(ME-987): notifications CLI support

cmd/organization.go
Fix typo in the event type.
Tested locally
=> fix: fix typo in event type

.github/workflows/build_and_release.yml, .github/workflows/run_tests.yml
Updates go version that tests are run with
Fixes:
- https://mysocket.atlassian.net/browse/ME-1176
N/A
[ME-1176]: https://mysocket.atlassian.net/browse/ME-1176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-1176] Update Go Version in Workflows

internal/api/api.go, internal/api/models/requests.go, internal/border0/socket.go, internal/connector/core/core_test.go, mocks/api_mock.go
Use provided hostKey to verify tunnel server.
Fixes # ME-1189
=> fix(ME-1189): use provided hostKey to verify tunnel server

.github/workflows/build_and_release.yml, Dockerfile, README.md
We have created Docer package and published it for our users on ghcr.io
- Epand package tags by BRANCH and RELEASE
- Expanding Docker usage documentation
- Shifting binary to / and calling border0 in ENTRYPOINT
- update to aws-actions/configure-aws-credentials@v2
- adding more info to action title
- swapping out the tags
- Adding MacOS(darwin) amd64 and arm64 platforms
In staged branch
=> GitHub Container Registry package for Border0 (ME-1225)

cmd/connect.go, cmd/root.go, cmd/socket.go, go.mod, go.sum, internal/api/models/socket.go, internal/border0/socket.go, internal/connector/config/config.go, internal/connector/core/core.go, internal/connector/discover/data_tag.go, internal/connector/discover/docker.go, internal/connector/discover/ec2.go, internal/connector/discover/k8.go, internal/connector/discover/static_sockets.go, internal/ssh/Shellsession.go, internal/ssh/proxy.go, internal/ssh/shellsession.go
add ssh auth proxy and aws session manager support.
Fixes # ME-1206
=> feat(ME-1206): add ssh auth proxy and aws session manager support

internal/ssh/server_unix.go
this detects if the OS is alpine, and provides a different log in command, ie. no shell provided.
This prevents this from happening (asking for local password)
```
$ border0 client ssh  -l root
? choose a host: ssh-connector-lab.border0.app [created by andree]
Connecting to Server: ssh-connector-lab.border0.app:22577 as root
Password:
Login incorrect
7f2f8243e8ab login: %
```
- [ x] Bug fix (non-breaking change which fixes an issue)
Tested locally
- [ x] My code follows the style guidelines of this project
=> Fix for ssh on alpine

internal/api/models/socket.go, internal/connector/core/core.go, internal/connector/discover/ec2.go
set upstreamType in connector mode
Fixes # ME-1350
Tested locally
=> fix(ME-1350): set upstreamType in connector mode

internal/ssh/server_unix.go
clear supplementary groups
Fixes # ME-1354
Test locally
=> fix(ME-1354): clear supplementary groups

internal/ssh/server_unix.go
only clear groups if run as root
Fixes # ME-1354
- [] New feature (non-breaking change which adds functionality)
Tested locally
=> fix(ME-1354): only clear groups if run as root

cmd/idp/cmd_idp_disable.go, cmd/idp/cmd_idp_enable.go, cmd/idp/common.go, cmd/idp/root_idp.go, go.mod
Allows toggling the microsoft global idp via the CLI.
- https://mysocket.atlassian.net/browse/ME-1480
```
12:20 $ ./border0 organization idp list
Global:
+-----------+---------+
| NAME      | ENABLED |
+-----------+---------+
| Google    | true    |
| GitHub    | true    |
| Microsoft | true    |
+-----------+---------+
Custom:
+-------------------+-----------------+------------------+---------+
| NAME              | DISPLAYNAME     | TYPE             | ENABLED |
+-------------------+-----------------+------------------+---------+
| Okta-Free-Trial   | Okta Free Trial | okta-workforce   | true    |
| MyGoogleWorkspace | My Company Auth | google-workspace | true    |
+-------------------+-----------------+------------------+---------+
```
```
12:20 $ ./border0 organization …
```
=> [ME-1480] Support Toggling Microsoft Authentication on/off

cmd/connector.go, internal/api/models/socket.go, internal/connector/config/config.go, internal/connector/config/config_test.go, internal/connector/config/testdata/config.yml, internal/connector/core/core.go, internal/connector/core/core_test.go, internal/connector/service.go
this allows for 3 new global config properties (provider-*)
```
connector:
name: bofh-aws
provider-type: aws
provider-enviroment: production
provider-region: us-east-2
```
=> ME-1491  Cloudtags

internal/api/models/socket.go
=> ME-1491 Fix for cloudtags

LICENSE
...as on the tin...
N/A
N/A
N/A
N/A
=> Apache License Template

cmd/client/db/db.go, cmd/client/db/mysql_workbench.go, internal/client/client.go, internal/client/sqlclientproxy/mysql.go, internal/client/sqlclientproxy/postgres.go, internal/client/sqlclientproxy/proxy.go
client local listener support for database sockets
Fixes # ME-1638
Tested locally with postgres and mysql.
=> feat(ME-1638): client local listener support for database sockets

internal/client/sqlclientproxy/mysql.go
=> add interface compliance check

Makefile
add build for linux arm v6
Fixes # ME-1646
=> chore(ME-1646): add build for linux arm v6

internal/connector/core/core.go
make connector compatible with 32bit arm
Fixes # (ME-1646)
Tested on armv7
=> fix(ME-1646): make connector compatible with 32bit arm

cmd/client/db/db.go
add local listener as db client option
tested locally
=> feat(ME-1638): add local listener as db client option

Makefile
Add support for openbsd amd64
Fixes # ME-1649
Needs testing on the openbsd platform
=> chore(ME-1649): add support for openbsd

Makefile
Reverts borderzero/border0-cli#98
=> Revert "chore(ME-1649): add support for openbsd"

internal/connector/core/core.go
fix: check the connector data before use it
=> fix: check the connector data before use it

Makefile, internal/connector/config/config.go, internal/connector/service.go
updates for alternative provider environment field in connector metadata 
tested manually in the lab with all permutations
=> ME-1659: OPS updates to the connector config loader

internal/http/server.go
Improved look and feel for fileserver 
=> ME-1671 Fileserver look and feel

cmd/root.go, cmd/socket.go, go.mod, go.sum, internal/api/models/socket.go, internal/connector/config/config.go, internal/connector/core/core.go, internal/connector/discover/ec2.go, internal/connector/discover/static_sockets.go, internal/ssh/proxy.go
Support for aws EC2 Connect upstream method
Fixes # ME-1629
Tested locally
=> feat(ME-1629): support for aws ec2 connect

go.mod, go.sum, internal/ssh/proxy.go
Removes checking because:
- Logic is bugged: when using an assumed-role, the policy evaluation incorrectly fails
- It requires the IAM entity to have the iam permission `iam:SimulatePrincipalPolicy` which they may not have; and is not at all needed for to start a session against an ssm target. If your IAM entity does not have this permission in one of their policies, aws will complain with `Error: error simulating principal policy operation error IAM: SimulatePrincipalPolicy, https response error StatusCode: 403, RequestID: 4105570d-bad4-49e0-b12d-54e7754dda9c, api error AccessDenied: User: arn:aws:sts::${AWS_ACCOUNT_ID}:assumed-role/SSM-TO-INSTANCE-ROLE/ROLE-1689201227 is not authorized to perform: iam:SimulatePrincipalPolicy on resource: …
=> [MISC] Remove Policy Simulation for SSM

cmd/policy.go
Removes a stray print statement in the policies cmd tree
N/A
N/A
=> [MISC] Removes a stray print statement in the policies cmd tree

internal/connector_v2/service.go
- using the connector config to ssh connect with (ec2-connect, aws-ssm, username and password, ssh private key and border0 certificate
=> [ME-1694] initial work to make the ssh methods available in connector v2

go.mod, go.sum, internal/api/models/socket.go, internal/connector_v2/service.go, internal/ssh/proxy.go
- using a new field to grab the private key in memory and pass to the proxy instead of the upstream identity file
=> [ConnectorV2] Support private key to connect in the box

internal/api/api.go
improve refresh token error handling
Fixes # (ME-1716)
Tested locally
=> fix(ME-1716): improve refresh token error handling 

go.mod, go.sum, internal/connector_v2/upstreamdata/builder.go
- accepting username as a optional parameter in border0 certificate option for connector v2
=> [ME-1738][Connector] allow username in border0 certificate option

cmd/client/httpproxy/httpproxy.go, go.mod, go.sum
Removing TUI code
better error handling when remote side goes away
=> ME-1786 removing TUI view and better error handlin

client/preference/preference.go, cmd/client/db/datagrip.go, cmd/client/db/dbeaver.go, cmd/client/db/mysql_workbench.go, cmd/client/ssh/keysign.go, cmd/client/ssh/ssh.go, internal/client/client.go, internal/client/resources.go, internal/http/handler.go, internal/util/osuser.go
This fix makes sure we use the correct homedir
if you use sudo, we will make sure to the original users homedir ie. env SUDO_USER
=> ME-1788 fixhomedir Make sure we use the correct homedir

cmd/connector.go, internal/api/api.go, internal/api/models/connector.go, internal/connector_v2/install/aws.go, internal/connector_v2/install/aws_cfn_template.go
An AWS CloudFormation based installer for connector v2
```
✔ ~/go/src/github.com/borderzero/border0-cli [ME-1807_cloud_install_v2 L|✚ 5…2]
18:52 $ AWS_PROFILE=demo ./border0 connector install --aws
-------------------------------------------------------------
Welcome to the Border0 Connector Installation Wizard for AWS!
-------------------------------------------------------------
? Which AWS region would you like to install a connector in? us-east-1
? Which VPC would you like to install the connector in? vpc-HIDDEN [172.31.0.0/16] (default)
? Which VPC subnet would you like to install the connector in? subnet-HIDDEN [us-east-1d 172.31.0.0/20]
? What name would you like for your new Border0 Connector? my-connector-1691545945
? What is the SSM parameter store path you'd like your border0 …
```
=> [ME-1807] Connector Cloud Install (AWS) - V2

cmd/connector.go
On MacOS, the hostname contains a `.` which results in an invalid socket name during install.
- N/A, bug
Locally on macOS
=> [HOTFIX] MacOS Hostname Issues

cmd/connector.go
- https://mysocket.atlassian.net/browse/ME-1808
Locally.
[ME-1808]: https://mysocket.atlassian.net/browse/ME-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-1808] Only Login User During Install if Full Install

internal/vpnlib/vpnlib.go
A connection can go down for many reasons, like in the example i ran into, a laptop going to sleep.
We should stop the loop on any of those errors. at that point the Conn is gone and we should disconnect
=> ME-1788 better catching of unexpected disconnects

go.sum, vendor/github.com/borderzero/border0-go/service/connector/types/upstream_config.go, vendor/modules.txt
Upgraded a library without running `go mod vendor` after
N/A
N/A
=> [HOTFIX] Handle inconsistent vendoring

internal/connector/core/core.go
- https://mysocket.atlassian.net/browse/ME-1816
Tested against API with various update scenarios.
[ME-1816]: https://mysocket.atlassian.net/browse/ME-1816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-1816] Add debug logs for socket updates

internal/client/client.go
Remove sleep and debug print and reuse connector auth function.
Fixes # ME-1744
Tested locally with and without wspoxy setting.
=> remove sleep and debug and reuse function

.github/workflows/build_and_release_deb_repo.yml, .gitignore, DEBIAN/postinst, DEBIAN/postrm, Makefile, README.md, build-deb.sh, generate-gpg.sh, generate-release.sh, release.conf
Adding deb packages creation with signed repo in s3 under downloads.border0.com/repos/
tested locally and on EC2
apt-g update, updrage and remove passes
=> ME-1777: creating deb packages and signed repo in s3

.github/workflows/build_and_release_deb_repo.yml
Fixing GH action syntax, file filters starting with wildcard are not allowed
n/a, syntax fix
=> FIX: GH Action workflow file syntax

.github/workflows/build_and_release_deb_repo.yml
Adding elevated execution for env seup
N/A
=> FIX: GH Action workflow permissions and elevated execution

.github/workflows/build_and_release_deb_repo.yml
all apt commands need sudo
N/A
=> FIX: GH Action tasks need elevated execution

DEBIAN/postrm
Validating debian repo build and release process
NOOP
=> ME-1777: NOOP update, validating build and release process

.github/workflows/build_and_release_rpm_repo.yml, Makefile
WE are creating RPM specific github action
tested manually on local system
=> ME-1856: RPM repo GH Action

internal/connector/core/core.go
- there is a bug checking the upstream http hostname values, we should not compare the pointers, instead compare the values
=> fix: check the real upstream value not the pointer

DEBIAN/postinst, DEBIAN/postrm
ME-1776: create symlink to /usr/bin/border0 for backwards compatibility
n/a
=> ME-1776: create symlink to /usr/bin/border0 for backwards compatibility

CENTOS/post-install.sh, CENTOS/post-uninstall.sh, DEBIAN/postinst, DEBIAN/postrm
we are removing  references for legacy path in /usr/local/bin
n/a
=> remove references for legacy path

internal/connector_v2/install/aws_cfn_template.go
- Uses the (normal) AL 2023 AMI, instead of the minimal one (minimal does not have ec2 instance connect script)
- Adds permission to push ssh public keys to all ec2 instances in the account
- Adds permission to allow starting and terminating SSM sessions to all ec2 instances in the account
Fixes:
- https://mysocket.atlassian.net/browse/ME-1895
- https://mysocket.atlassian.net/browse/ME-1896
This has been tested by installing the new connector with this template and ensuring ec2 instance connect and ec2 works.
[ME-1895]: https://mysocket.atlassian.net/browse/ME-1895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-1895][ME-1896] Connector V2 Cloud Installer Improvements

internal/connector_v2/install/aws_cfn_template.go
Few changes to the CFN template used by the AWS Installer for Connector V2:
- Removes the AWS-Managed SSM ReadOnly Policy (we don't need it, it's too permissive)
- Adds a managed policy for the EC2 instance to register itself with SSM (as a means for breakglass access without needing network ingress)
- Removes the development parameters to set a non-production api and proxy urls 
- https://mysocket.atlassian.net/browse/ME-1898
Tested running the installer against my aws account. Was able to connect to other instances using the connector, with aws ssm and ec2 instance connect. 
[ME-1898]: https://mysocket.atlassian.net/browse/ME-1898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-1898] Run SSM Agent in AWS-Installer Connector Instances

go.mod, go.sum, internal/connector_v2/service.go, vendor/github.com/borderzero/border0-go/types/service/configuration.go, vendor/modules.txt
Read `ConnectorAuthenticationEnabled` flag from gRPC `SocketConfig`
Manual test with Border0 API
=> ME-1893: read connector auth flag from socket config

internal/connector_v2/install/aws.go
Check AWS SSM Parameters before suggesting a default name (to ensure that the suggested name is unique / does not exist yet).
Also, shorter default names for everything we create automatically. e.g. `border0-connector-cloud-install-aws-%d` --> `border0-aws-connector-%d`
- https://mysocket.atlassian.net/browse/ME-1909
Used the modified CLI code to install two connectors and saw that the default suggested ssm parameter for the second connector was unique.
[ME-1909]: https://mysocket.atlassian.net/browse/ME-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-1909] Check SSM Param Name for Uniqueness Before Proposing Default

.github/workflows/build_and_release.yml, cmd/root.go
Fix `--version` flag.
Manually tested with local build.
=> ME-1954: fix `--version` flag

cmd/connect.go, cmd/run.go, cmd/socket.go, cmd/tunnel.go, internal/border0/socket.go, internal/connector/core/core.go, internal/connector_v2/service.go, internal/ssh/connect.go, internal/ssh/proxy.go, internal/ssh/shellsession.go, vendor/golang.org/x/crypto/ssh/certs.go
generate and store hostkey for connector v2
Fixes # (ME-1894)
=> feat(ME-1894): generate and store hostkey for connector v2

cmd/child.go, internal/ssh/server.go
=> fix(ME-1981)

.github/workflows/build_and_release.yml, go.mod, go.sum, vendor/github.com/borderzero/discovery/discoverers/discoverer_network.go, vendor/modules.txt
Upgrade discovery library for rdp discovery enhancements
- https://mysocket.atlassian.net/browse/ME-2012
Locally on my machine and running an xRDP server as the target for discovery
[ME-2012]: https://mysocket.atlassian.net/browse/ME-2012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2012] Upgrade Discovery Lib

internal/ssh/server.go, internal/ssh/server_unix.go, internal/ssh/server_windows.go
basic sftp support on windows
Fixes # ME-1981
Tested on windows (yvr)
=> feat(ME-1981): basic sftp support on windows

.github/workflows/build_and_release.yml, Makefile
Add windows arm64 build target
Test with Makefile
=> ME-2103: add windows arm64 build target

.github/docker/Dockerfile, .github/workflows/build_and_release_rpm_repo.yml, build-rpm.sh
we are bringing RPM to parity deb DEB repo
```
$ find rpm/
rpm/
rpm/border0.repo
rpm/x86_64
rpm/x86_64/border0-1.1-501.g4dcc494.el9.x86_64.rpm
rpm/i386
rpm/i386/border0-1.1-501.g4dcc494.el9.i386.rpm
rpm/aarch64
rpm/aarch64/border0-1.1-501.g4dcc494.el9.aarch64.rpm
rpm/repodata
rpm/repodata/2d396e488cd2a336bc342cc27f0db35c66cd11dea9d6210458207f83146183c6-filelists.xml.gz
rpm/repodata/3784b5138d736885be9528ba66fa040c259a56e5b167f1270b55a16c6ca50c9e-filelists.sqlite.bz2
rpm/repodata/repomd.xml.asc
rpm/repodata/repomd.xml
rpm/repodata/851efa9c26257e8c4d168a1742f533fa25ce7f835a1b0145c7b5d71d93fce02b-other.sqlite.bz2
rpm/repodata/c7062340bf7351931cf114754c8fec2c423fdf7dd817599e5520545de6b2f2e4-primary.sqlite.bz2
rpm/repodata/8721b5a56f1cfed1cef1319a0bd51cc986b8e69224c4d5e142b4c330 …
```
=> ME-2119 multiarchitecture RPM repo

.github/workflows/build_and_release.yml, .github/workflows/build_and_release_deb_repo.yml, .github/workflows/build_and_release_rpm_repo.yml, build-deb.sh, release.conf
=> ME-2081: one border0 Action across binary, ECS and OS artefacts

cmd/child.go, internal/process/setup.go, internal/process/setup_windows.go, internal/ssh/server.go, internal/ssh/server_unix.go
close command after ssh session is closed
Fixes # (ME-2080)
Tested locally, with client portal, ssh, sftp and ansible.
=> fix(ME-2080): close command after ssh session is closed

cmd/version.go
=> New release to test upgrade

go.mod, go.sum, vendor/github.com/aws/session-manager-plugin/src/sessionmanagerplugin/session/session.go, vendor/github.com/borderzero/discovery/discoverers/discoverer_aws_ecs.go, vendor/github.com/borderzero/discovery/resource.go, vendor/modules.txt
Upgrades discover library version (which adds cluster name to ecs services discovered)
- https://mysocket.atlassian.net/browse/ME-2129
N/A
[ME-2129]: https://mysocket.atlassian.net/browse/ME-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2129] Bump Discovery Lib

Dockerfile
Updating MOTD, links to docs, help pages and support
N/A updating motd text
=> Updating MOTD, links to docs, help pages and support (ME-2154)

cmd/client/db/pgcli.go, cmd/client/db/psql.go, go.mod, internal/client/sqlclientproxy/postgres.go, internal/sqlauthproxy/handler.go, internal/sqlauthproxy/mysql_local_handler.go, internal/sqlauthproxy/postgres.go, internal/sqlauthproxy/postgres_copy_handler.go, internal/sqlauthproxy/postgres_local_handler.go, internal/sqlauthproxy/recording.go, vendor/github.com/aws/session-manager-plugin/src/sessionmanagerplugin/session/session.go
Postgres e2e encryption support
Fixes # (ME-1977)
Tested in staging
=> feat(ME-1977): postgres e2e encryption support

internal/sqlauthproxy/recording.go, internal/ssh/session/recording.go
upload recordings on interval, now it's set to 30s or size is over 10MB.
Fixes # (ME-2223)
Tested in staging.
=> feat(ME-2223): upload recordings on interval

cmd/socket.go, cmd/tunnel.go, internal/api/api.go, internal/api/models/requests.go, internal/border0/socket.go, internal/connector/core/core.go, internal/connector/service.go, internal/connector_v2/service.go, internal/connector_v2/session.go, internal/sqlauthproxy/handler.go, internal/sqlauthproxy/mysql.go, internal/sqlauthproxy/mysql_local_handler.go, internal/sqlauthproxy/postgres.go, internal/sqlauthproxy/postgres_local_handler.go, internal/sqlauthproxy/recording.go, internal/ssh/session/local_session.go, internal/ssh/session/recording.go, internal/ssh/session/ssh_session.go, internal/ssh/session/ssm_session.go, internal/util/certificate.go, internal/util/hostkey.go, mocks/api_mock.go
e2e encryption support for socket connect and connector v1
Fixes # (ME-2215)
Tested on staging.
=> feat(ME-2215): e2e encryption support for socket connect and connector v1

internal/sqlauthproxy/mysql_local_handler.go
catch database change if use is used in a query
Fixes # (ME-2265)
=> fix(ME-2265): catch database change if use is used in a query

cmd/socket.go, internal/connector/core/core.go, internal/connector_v2/service.go, internal/util/certificate.go, internal/util/hostkey.go
fix store file function and continue socket if storing cert/hostkey fails
Fixes # (ME-2216)
Tested on staging.
=> fix(ME-2216): fix store file function and continue socket if storing cert/hostkey fails

internal/ssh/session/ssh_session.go
add ssh client keepalive, this will send a keepalive message every 30s.
Fixes #ME-2309
Tested on local build.
=> chore(ME-2309): add ssh client keepalive

internal/ssh/session/ssm_session.go
only send windowschange if ssm is connected
Fixes # (ME-2316)
Tested with local build
=> fix(ME-2316): only send windowschange if ssm is connected

cmd/socket.go
e2ee support for socket connect vpn/proxy
Fixes # (ME-2215)
Tested in staging with proxy and vpn socket.
=> fix(ME-2215): e2ee support for socket connect vpn/proxy

go.mod, go.sum, vendor/github.com/borderzero/discovery/discoverers/discoverer_aws_ec2.go, vendor/github.com/borderzero/discovery/discoverers/discoverer_aws_rds.go, vendor/github.com/borderzero/discovery/discoverers/network_utils.go, vendor/github.com/borderzero/discovery/resource.go, vendor/modules.txt
Upgrades and re-vendors the discovery lib
[ME-2344]: https://mysocket.atlassian.net/browse/ME-2344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2344] Upgrade Discovery Lib For RDS Reachability Checks

internal/ssh/session/kubectl_exec_session.go
Mitigates the following possible closed channel usage scenario (happens when we close the channel before the k8s library closes) by delaying the closing of the channel:
- https://mysocket.atlassian.net/browse/ME-2411
```
autumn-bird - https://client.border0.com/#/ssh/autumn-bird-reinvent.border0.io
=======================================================
Logs
=======================================================
E1215 13:37:05.379283   55118 runtime.go:79] Observed a panic: "close of closed channel" (close of closed channel)
goroutine 1901 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x104151480?, 0x104762ee8})
/home/runner/work/border0-cli/border0-cli/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x7c …
```
=> [ME-2411] Fix Use of Closed Channel

internal/connector_v2/service.go
Prior to this change, errors during initialization (e.g. setting up plugins and/or sockets) would cause the connector to restart. If the cause of the error was persistent, the connector would enter a restart loop that would only stop when the cause of the error is addressed.
For example, a customer enabled an AWS discovery plugin for a connector deployed in digital ocean. AWS region/config could not be deduced and thus the connector would just fail and restart in a loop - never being able to set up sockets or other plugins (which would not error out).
- https://mysocket.atlassian.net/browse/ME-2483
This has been tested by enabling the AWS discovery plugins in a connector deployed in a Docker container with no AWS credentials. The connector comes up even though the plugin …
=> [ME-2483] Make Init Errors Non-Fatal

internal/connector/core/core.go, internal/connector_v2/service.go, internal/util/certificate.go, internal/util/hostkey.go
fix hostkey loading
Fixes # (ME-2495)
Tested with local build
=> fix(ME-2495): fix hostkey loading

internal/connector/core/core.go, internal/connector_v2/service.go, internal/util/certificate.go, internal/util/hostkey.go
This reverts commit c43535e6000c992186344b3688ab0e0eec83cf04.
=> Revert "fix(ME-2495): fix hostkey loading"

cmd/idp/cmd_idp_disable.go, cmd/idp/cmd_idp_enable.go, cmd/idp/common.go, cmd/idp/root_idp.go
> Note: this PR was done with the aid of the previous example of adding a new global idp (microsoft) here https://github.com/borderzero/border0-cli/pull/81
Supports enabling/disabling the "Email Code" identity provider.
- https://mysocket.atlassian.net/browse/ME-2517
Built locally and pointed to a test account in staging:
```
✔ ~/go/src/github.com/borderzero/border0-cli [ME-2517_support_email_idp_toggle L|✚ 4]
10:26 $ ./border0 organization idp list
Global:
+------------+---------+
| NAME       | ENABLED |
+------------+---------+
| Google     | true    |
| GitHub     | true    |
| Microsoft  | true    |
| Email Code | false   |
+------------+---------+
✔ ~/go/src/github.com/borderzero/border0-cli [ME-2517_support_email_idp_toggle L|✚ 4]
10:26 $ ./border0 organization idp …
```
=> [ME-2517] Suport Email IDP Toggle

internal/util/certificate.go
remove print
Fixes # (ME-2495)
=> fix: remove print

cmd/client/vpn/vpn.go, cmd/socket.go, internal/vpnlib/tun_linux.go, internal/vpnlib/tun_other.go, internal/vpnlib/tun_windows.go, internal/vpnlib/vpnlib.go
Various fixes for DNS, IPv6 and BSD. Sticking with our water fork for now.
=> ME-2597 fixing build for BSD and some dns and v6 fixes

cmd/client/ssh/ssh.go
As part of our external pentest we were asked to allowlist `Origin` header values server side. We think that adds no security -- but we did it anyways to comply and avoid having a no-win discussion.
Now we have to set origin headers in any client of the websocket server. Failure to do so will result in a 403 from the websocket server.
- https://mysocket.atlassian.net/browse/ME-2611
Didn't work before the change, now it does.
[ME-2611]: https://mysocket.atlassian.net/browse/ME-2611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2611] Set Origin Header for WS Proxy

internal/border0/socket.go
add version information in tunnel
Fixes # (ME-2627)
Tested local
=> fix(ME-2627): add version information in tunnel

internal/ssh/server/server_unix.go
add workaround for amazon linux ssh read error
Fixes # (ME-2670)
Tested on amazon linux and ubuntu
=> fix(ME-2670): add workaround for amazon linux ssh read error

cmd/socket.go, internal/vpnlib/server.go, internal/vpnlib/vpnlib.go
Readability + reusability improvements.  Using common `net` and `io` interfaces where possible.
- part of https://mysocket.atlassian.net/browse/ME-2657
Tested on MacOS and Debian
[ME-2657]: https://mysocket.atlassian.net/browse/ME-2657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2657] VPN Server Refactor

cmd/client/vpn/vpn.go, internal/client/client.go, internal/client/resources.go
Adds reconnection logic to the VPN client. Cleans up the code a little bit too.
- https://mysocket.atlassian.net/browse/ME-2684
This has been tested on MacOS and Debian
[ME-2684]: https://mysocket.atlassian.net/browse/ME-2684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2684] VPN Client Reconnect Attempts

cmd/client/vpn/vpn.go
Fixes 2 bugs:
- Before:
- We would always try to set a route on the default v4 gateway to talk to the VPN gateway through it (which would not work for IPv6 and would just spit our an error log)
- We would try to set routes on the default v4 gateway to keep talking to DNS servers through it ONLY if the VPN gateway had an IPv4
- Now
- We only set a route on the default v4 gateway to talk to the VPN gateway through it if the vpn gateway has a V4 address (no need to do it for V6 because the VPN will never advertise V6 routes)
- We ALWAYS set routes on the default v4 gateway to keep talking to DNS servers through it
- https://mysocket.atlassian.net/browse/ME-2684
Tested in MacOS client and Debian server
[ME-2684]: https://mysocket.atlassian.net/browse/ME-2684?atlOrigin=eyJpIjoiN …
=> [ME-2684] VPN: Fix Logic For Adding Additional Routes in Default Gateway

cmd/client/utils/local_proxy_and_client.go
If a local listener port is provided via flag, then we do not open the client and we keep the listener running.
If a local listener port is NOT provided via flag, then we do open the client and bail after any error.
[ME-2711]: https://mysocket.atlassian.net/browse/ME-2711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2711] Exit Local Listener After One Fail

internal/connector_v2/install/local.go
Fix unintended behaviour change in previous commit.
- https://mysocket.atlassian.net/browse/ME-2727
-  [X] Bug fix (non-breaking change which fixes an issue)
deb packages were broken by this change - no more.
[ME-2727]: https://mysocket.atlassian.net/browse/ME-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ME-2727] Only Try Retrieve Connector Invite Code When Provided
