borderzero/border0-cli

- .github/workflows/go.yml
- .github/workflows/manual-go.yml
- Adding secret for CF cache flush
- Expanding GH actions to clear CF cahe after build/release to S3 
- Allowing manual trigger of all actions
- Restricting main push trigger to GO code paths
> Expanding GH Actions with CloudFront cache invalidator

- internal/connector/discover/docker.go
policies are not attached to sockets in docker plugin, so, plugin needs to add them to the core
> [Connector] Add policies to docker plugin

- internal/connector/discover/data_tag.go
- internal/connector/discover/docker.go
- internal/connector/discover/ec2.go
Summary
- support name in the docker and EC2 tags to avoid name collision, with that we can have multiples sockets with different name in same container or instance
> [feat] support multiple names in connector plugins

- .github/workflows/go.yml
- .github/workflows/manual-go.yml
- Makefile
We are changing the way binary artefact versioning is generated and used thru the build process.
Previously the version string was being generated with each invocation of make command, we are changing that.
The version is now created at the beginning of the Github action and stored in environment variable for make command to reuse thtu the build process.
> OPS: update github actions binary artefact version generation logic

- internal/connector/discover/data_tag.go
- internal/connector/discover/docker.go
- internal/connector/discover/ec2.go
This implements parsing of ```upstream_*```  tags used in database sockets
labels such as:
```
"border0_01": "type=database,port=3306,group=infra_team,upstream_type=mysql,upstream_username=root,upstream_passpassword=my-secret-pw"
```
create functioning database sockets in Docker and EC2 plugins
> FIX: add support for upstream_* tags in docker and EC2 plugins

- cmd/policy.go
We tried to get the email from the token, but API tokens dont have email address.
> FIX creating new policy when using API tokens

- internal/api/api.go
- internal/client/resources.go
- internal/http/handler.go
we are adding 2 envarionemnt variables for admin and client tokens BORDER0_ADMIN_TOKEN - access adming tokens, more details: https://docs.border0.com/docs/creating-access-token BORDER0_CLIENT_TOKEN - curently in development, this is client side token for frontend socket access
sample usage with docker:
```
docker run -e BORDER0_ADMIN_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ey<...>J9.qJ75mbolje96zpD9gnOnhCKTSBoEjIGDdMMeteZ7RJQ" border0:latest /code/border0 socket connect --type ssh --name border0-bastion --sshserver
```
or with docker-compose:
```
border0_bastion:
build:
context: "."
dockerfile: "Dockerfile.border0_bastion"
container_name: "border0_bastion"
environment:
- BORDER0_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ey<...>J9.qJ75mbolje96zpD9gnOnhCKTSBoEjIGDdMMeteZ7RJQ
```
> FEAT: add BORDER0_ token environment variables

- cmd/login.go
TL;DR; There's currently a duplicate message whenever opening the browser fails during the handler for `border0 login`
Need to run the border0 cli in a system without a browser, so I'm running it in a barebones Alpine Linux docker container.
e.g. dockerfile:
```
FROM alpine:latest
RUN apk add --update bash curl && rm -rf /var/cache/apk/*
RUN curl https://download.border0.com/linux_arm64/border0 -o /usr/local/bin/border0
RUN chmod +x /usr/local/bin/border0
CMD ["border0", "login"]
```
After building with `docker build . -t ${IMAGE_NAME}`
`docker run ${IMAGE_NAME}` yields:
```
please login with the link below:
https://portal.border0.com/login?device_identifier=${HIDDEN_CLIENT_GENERATED_DEVICE_IDENTIFIER}
failed opening browser. Open the url …
```
> Get rid of duplicate URL on 'border0 login' when opening browser fails

- internal/ssh/server.go
stop logging error because multiple public certs could be given to ssh server, and some pub certs may not be valid
> ssh: suppress ssh public cert validation error message

- internal/client/resources.go
This PR introduces new behavior for the `border0 client login` command such that the authorization flow now conforms to the OAuth2.0 device authorization flow https://www.rfc-editor.org/rfc/rfc8628 (and thus supports headless authentication).
This has been well tested against the border0 API.
Some scenarios:
```
✔ ~/go/src/github.com/adrianosela/border0-cli [main|✚ 1]
14:49 $ ./border0 client login
? choose an org: anything
Please navigate to the URL below in order to complete the login process:
https://api.staging.border0.com/api/v1/client/auth/org/anything?device_identifier=${HIDDEN_CODE}
Error: Authenticated user is not authorized for organization "anything"
```
```
✔ ~/go/src/github.com/adrianosela/border0-cli [main|✚ 1]
14:49 $ ./border0 client login
? choose an org: anything
Please …
```
> Headless client login (device auth code flow)

- .github/workflows/go.yml
- .github/workflows/manual-go.yml
on build and release in this cli repo
- trigger `mysocketio/client` repo to build and release, that will ensure the latest cli gets bundled into desktop app packages
- trigger `mysocketio/client` repo to create a new pr to bump the desktop app version, once the pr gets merged, existing desktop app users will get notified to download the new version with the latest cli bundled
Tested both github workflow steps in a separate github repo, and successfully get both cross repo workflows triggered.
> ME-921: github actions to trigger desktop app build

- cmd/client/db/pgcli.go
- cmd/client/db/psql.go
- internal/client/client.go
- internal/client/resources.go
This PR fixes the issue where border0 client db can not be used with postgres and custom domains.
Fixes # ME-978
This has been tested locally with both custom domains and default domains.
> fix: only use root cert to validate certificate chain, and remove deprecated ioutil package

- .github/workflows/build_and_release.yml
Release job is failing with `fatal: No names found, cannot describe anything.`
See https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything
Here we modify the github action that checks out the code to do a deep clone of the repo instead of the default shallow clone (fetches a single commit only).
- https://mysocket.atlassian.net/browse/ME-1012
It does not affect the released software, so it'll be tested when its merged.
[ME-1012]: https://mysocket.atlassian.net/browse/ME-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1012] CI: Deep clone repo

- cmd/idp/cmd_idp_add_googleworkspace.go
- cmd/idp/cmd_idp_add_oidc.go
- cmd/idp/cmd_idp_add_oktaworkforce.go
- cmd/idp/cmd_idp_add_saml.go
- cmd/idp/cmd_idp_enable.go
- cmd/idp/cmd_idp_list.go
- cmd/idp/cmd_idp_show.go
- cmd/idp/cmd_idp_update_googleworkspace.go
- cmd/idp/cmd_idp_update_oidc.go
- cmd/idp/cmd_idp_update_oktaworkforce.go
- cmd/idp/cmd_idp_update_saml.go
- cmd/idp/common.go
- cmd/idp/root_idp_add.go
- cmd/idp/root_idp_update.go
- Adds support for setting/updating/getting/listing display names for identity providers; which need not be unique and are of a much more permissive format than names.
- Fixes a bug in the `enable` command where it was checking flags for the disable command instead of its own.
- Fixes the description of the update flags where they had copy-pasta fails from the add command's flags
- https://mysocket.atlassian.net/browse/ME-1011
Against a local api with the changes here: https://github.com/mysocketio/api/pull/749
[ME-1011]: https://mysocket.atlassian.net/browse/ME-1011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1011] Custom IDPs: Display Name Support

- cmd/client/ssh/ssh.go
A friendlier error message when not authorized for an ssh socket
```
18:15 $ ./border0 client ssh --host mysshsocket-adrianosela.staging.border0.io
Connecting to Server: mysshsocket-adrianosela.staging.border0.io:11054 as adriano
Error: ssh handshake failed (EOF): you might be unauthorized for this server
Usage:
border0 client ssh [flags]
Flags:
-h, --help              help for ssh
--host string       The ssh border0 target host
-l, --login string      Same as username, specifies the user login to use on remote machine
-u, --username string   Specifies the user to log in as on the remote machine(deprecated)
```
- none, purely aesthetic 
Tested against staging and production servers
> Friendly error message on ssh handshake

- internal/client/resources.go
A friendlier error message when not authorized for an ssh socket
```
$ border0 client ssh
Error: couldn't capture host input: please provide options to select from
Usage:
border0 client ssh [flags]
Flags:
-h, --help              help for ssh
--host string       The ssh border0 target host
-l, --login string      Same as username, specifies the user login to use on remote machine
-u, --username string   Specifies the user to log in as on the remote machine(deprecated)
```
```
$ ./border0 client ssh
Error: No hosts available to connect to
Usage:
border0 client ssh [flags]
Flags:
-h, --help              help for ssh
--host string       The ssh border0 target host
-l, --login string      Same as username, specifies the user login to use on remote machine
-u, --username string   Specifies the …
```
> Friendly error message on no available ssh hosts

- client/preference/data.go
- client/preference/data_test.go
Preference package should ignore org with `<nil>` subdomain. This PR fixes the bug that's illustrated in the following screenshot.
Before the fix:
After the fix:
- Unit tests
- Compiled the CLI and tested manually with `border0 client login`
> bugfix: preference should ignore org with <nil> subdomain

- internal/connector/core/core.go
- internal/connector/core/core_test.go
- internal/ssh/connect.go
- with tunnelless sockets we don't need to pre create the tunnels
- this improves the socket connected engine using a socket_id instead of a pre generated key from the information tags
> [Connector] use sockets without pre created tunnels

- cmd/connector.go
- cmd/login.go
- cmd/root.go
- go.mod
- go.sum
- internal/api/models/token.go
we are adding new functionality to the border0 cli tool
- border0 conenctor install
- border0 connector uninstall
above commands manage system level service for the connector installation creates connector token and requires border0.com account bare bones default config is also created, enabling built-in ssh server functionality
manually in staging and the lab
> (ME-1297) Adding support for connector service

- internal/border0/socket.go
Fixes a bug in connector where if the `sck.IsClosed()` is called prior to `sck.Listen()` -- we run into a nil pointer dereference.
Example stack trace:
```
Apr 25 14:41:27 rpi4-0 fcbdb9c34245[649]: 2023/04/25 21:41:27 creating a socket: mysql-6b7a3589p3306-pi4-0
Apr 25 14:41:27 rpi4-0 fcbdb9c34245[649]: 2023/04/25 21:41:27 creating a socket: mysql-6b3f6e94p3306-pi4-0
Apr 25 14:41:28 rpi4-0 fcbdb9c34245[649]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 25 14:41:28 rpi4-0 fcbdb9c34245[649]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x18b83f0]
Apr 25 14:41:28 rpi4-0 fcbdb9c34245[649]: 
Apr 25 14:41:28 rpi4-0 fcbdb9c34245[649]: goroutine 21 [running]:
Apr 25 14:41:28 rpi4-0 fcbdb9c34245[649]: …
```
> [ME-1331] Fix Nil Pointer in Socket Context

- internal/border0/socket.go
In https://github.com/borderzero/border0-cli/pull/71 the socket's context was changed to use the context passed to the constructor as the parent context. This behaviour is undesirable because cancelling the parent context SHOULD NOT cancel the socket's context.
This change moves us back to using `context.Background()` (a fresh context object) as the parent context argument in the `context.WithCancel()` function.
Note that all invocations of the socket constructor function are called with `context.Background()` as the `ctx` argument, so there is no real danger in the current behaviour -- this is more of a correctness change.
- https://mysocket.atlassian.net/browse/ME-1331
Running locally
[ME-1331]: https://mysocket.atlassian.net/browse/ME-1331?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
> [ME-1331] Use fresh context for socket state

- cmd/connector.go
Make sure the directory exist
when installing the connector, you sometimes see this error
```
ubuntu@definite-catbird:~$ sudo border0 connector install
Please navigate to the URL below in order to complete the login process:
https://portal.border0.com/login?device_identifier=ImQ3M2Q0YmZiLWEyMzYtNDk2My1hOTE5LTY1ZDQwMDFjN2RkZCI.ZGKdfA.tBa09dFJA88LzRx7tUbT_VzE2zw
Login successful
Error: open /home/ubuntu/.border0/token: no such file or directory
```
We need to make sure the dir exist
tested locallt
> ME-1446 connector fix

- go.mod
- go.sum
- lib/varsource/README.md
- lib/varsource/variable_source.go
- lib/varsource/variable_source_multiple_upstream.go
- lib/varsource/variable_upstream_aws_secretsmanager.go
- lib/varsource/variable_upstream_aws_ssm.go
- lib/varsource/variable_upstream_env.go
- lib/varsource/variable_upstream_file.go
A package for sourcing variable values from multiple upstreams.
Currently supported upstreams include:
- `env:` an environment variable value
- `file:` the contents of a file
- `aws:ssm:` an AWS Systems Manager Parameter Store parameter value
- `aws:secretsmanager:` an AWS Secrets Manager secret value
```
vs := varsource.NewDefaultVariableSource()
vars, err := vs.GetVariables(ctx, map[string]string{
"DB_USERNAME": "${env:DB_USERNAME}",
"DB_PASSWORD": "${aws:secretsmanager:my-password}",
}
// ... handle error ...
username := vars["DB_USERNAME"]
password := vars["DB_PASSWORD"]
// ... do something useful ...
```
- https://mysocket.atlassian.net/browse/ME-1421
Tested locally - needs unit tests.
[ME-1421]: https://mysocket.atlassian.net/browse/ME-1421?atlOrigin=eyJpIjoiNWRkNTljN …
> [ME-1421] Config Variable Sources Framework

- internal/connector_v2/config/README.md
- internal/connector_v2/config/config.go
- lib/varsource/variable_source.go
- lib/varsource/variable_source_multiple_upstream.go
Initial connector V2 configuration package boilerplate
- https://mysocket.atlassian.net/browse/ME-1421
Locally with the following test code:
```
package main
import (
"context"
"fmt"
"log"
"github.com/borderzero/border0-cli/internal/connector_v2/config"
"gopkg.in/yaml.v3"
)
func main() {
connectorConfig, err := config.GetConfiguration(context.Background())
if err != nil {
log.Fatalf("failed to get configuration: %v", err)
}
byt, err := yaml.Marshal(connectorConfig)
if err != nil {
log.Fatalf("failed to marshal config: %v", err)
}
fmt.Println(string(byt))
}
```
and the following test config file
```
token: asdfghj987654edfghjki8765
variables:
DB_USERNAME: user
DB_PASSWORD: password
```
[ME-1421]: https://mysocket.atlassian.net/browse/ME-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
> [ME-1421] Initial Connector (v2) Configuration

- cmd/connector.go
- go.mod
- go.sum
- internal/connector/config/config.go
In https://github.com/borderzero/border0-cli/pull/82, the imported module github.com/prometheus/procfs was upgraded from version `v0.9.0` to `v0.10.0`. Version `v0.10.0` introduced a bug which causes the module to fail to build binaries for `GOOS=windows`.
Hence the downgrade of that module via **this** PR.
I've opened a ticket against the upstream library's git repo https://github.com/prometheus/procfs/issues/527 explaining the issue and pointing them to the likely culprit of the problem.
We will upgrade this library again once they've fixed the problem.
Also in this PR: running go format (`gofmt -s -w`) to iron out formatting misses
Fixes:
- https://mysocket.atlassian.net/browse/ME-1493
Tested that the CLI builds for all our released OS/ARCH combinations: 
```
11:02 $ make release …
```
> [ME-1493] Fix build for GOOS=windows GOARCH=amd64

- internal/api/models/socket.go
if the socket type / upstream type is not provided we try to guess the value, but we are trying to guess the https types, but not the http one, so adding the http type to the guessing logic will fix the update loop in connector
> [ME-1543] fix connector upstream type guessing

- .github/workflows/build_and_release.yml
Extends the duration of the temporary credentials used to push built binaries and metadata.
Fixes:
- https://mysocket.atlassian.net/browse/ME-1647
N/A - job failed with expired creds after 20 minutes.
[ME-1647]: https://mysocket.atlassian.net/browse/ME-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1647] Extend build and release job temp creds duration

- cmd/client/db/datagrip.go
- cmd/client/db/db.go
- cmd/client/db/dbeaver.go
- internal/client/client.go
- internal/client/datagrip/data_sources.go
Support DataGrip as db client for MySQL and PostgreSQL databases. Also fixed GUI based db client launching on Windows.
Compiled CLI and:
- Tested with DataGrid on MacOS
- Shipped CLI binary to a Windows machine, and tested with DataGrid on Windows
- Tested db client launching with DataGrid, DBeaver and MySQL Workbench on Windows
> ME-1637: add db client support for datagrip

- go.mod
- go.sum
- internal/connector_v2/plugin/builder.go
- internal/connector_v2/plugin/plugin.go
Adds support for kubernetes service discovery (with the kubernetes discovery plugin) to connector v2.
Fixes:
- https://mysocket.atlassian.net/browse/ME-1667
This has been tested by pushing various forms of k8s configuration to the API and having the connector pick up and process the plugin configuration, resulting in discovered resources.
[ME-1667]: https://mysocket.atlassian.net/browse/ME-1667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1667] K8s Discovery Support in Connector V2

- go.mod
- go.sum
- internal/connector_v2/plugin/builder.go
- internal/connector_v2/plugin/plugin.go
Adds support for receiving configuration for docker discovery plugins from API
- https://mysocket.atlassian.net/browse/ME-1673
Tested locally by receiving docker discovery config from API in the border0 staging env.
[ME-1673]: https://mysocket.atlassian.net/browse/ME-1673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1673] Docker Discovery Support in Connector V2

- go.mod
- go.sum
- internal/connector_v2/plugin/builder.go
Accounts for changes to ecs discovery (no longer scanning clusters, scanning services)
- part of https://mysocket.atlassian.net/browse/ME-1679
Staging API + staging Portal + changes in CLI.
[ME-1679]: https://mysocket.atlassian.net/browse/ME-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1679] Changes to ECS Discovery (connector v2)

- go.mod
- go.sum
- internal/connector_v2/plugin/builder.go
- internal/connector_v2/plugin/plugin.go
- Upgrades versions of go sdk and discovery libraries to latest
- Configures network discovery based on new network discovery plugin schema
- Removes indirect dependency on nmap library
- part of https://mysocket.atlassian.net/browse/ME-1684
Connector connected to live api in border0 staging.
[ME-1684]: https://mysocket.atlassian.net/browse/ME-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1684] Network Discovery Support in Connector V2

- go.mod
- go.sum
- internal/connector_v2/plugin/builder.go
Wraps up first full pass at end-to-end network discovery. Had a bug where the targets were not being set at all.
- part of https://mysocket.atlassian.net/browse/ME-1684
```
✔ ~/go/src/github.com/borderzero/border0-cli [ME-1684_fix_network_discovery_bug|✔]
17:41 $ BORDER0_LOG_LEVEL=debug ./border0 connector start --v2
{"level":"info","ts":"2023-07-11T17:42:22-07:00","msg":"starting the connector service"}
{"level":"info","ts":"2023-07-11T17:42:22-07:00","msg":"connecting to connector server","server":"capi.staging.border0.com:443"}
{"level":"info","ts":"2023-07-11T17:42:22-07:00","msg":"new plugin","plugin":"72718bce-7a1c-4e33-84c5-82b149fced07"}
{"level":"debug","ts":"2023-07-11T17:42:30-07:00","msg":"discovery result","plugin_id":"72718bce-7a1c-4e33-84c5-82b149fced07","di …
```
> [ME-1684] Fix Network Discoverer Bug (Connector v2)

- go.sum
- internal/sqlauthproxy/postgres.go
Enable TLS in sqlproxy to support connector auth.
Fixes # ME-1668
Tested on staging.
> fix(ME-1668): enable tls in sqlproxy to support connector auth

- cmd/root.go
- cmd/socket.go
- go.sum
- internal/ssh/proxy.go
Removing availability zone because:
- The SDK does not require it
- It is optional under all circumstances in the send-public-key operation; seems to be left in the aws api/sdk/cli for backwards compatibility only
- Instance IDs are globally unique and are guaranteed not to change for a given instance
- One less option is a big win in terms of friction
- https://mysocket.atlassian.net/browse/ME-1718
Tested locally
```
Adrianos-MacBook-Pro:~ adriano$ AWS_PROFILE=default AWS_REGION=us-east-1 border0 socket connect demo-ec2-ic-socket --aws_ec2_connect --aws_ec2_target i-07ef34b7a4d50bb47 --host 44.203.135.224 --port 22
demo-ec2-ic-socket - ssh://demo-ec2-ic-socket-docs0.border0.io
=======================================================
Logs …
```
> [ME-1718] Remove Need for Useless Availability Zone Arg

- cmd/root.go
- cmd/socket.go
- internal/api/models/socket.go
- internal/ssh/proxy.go
Uses naming of AWS things in accordance to how AWS calls things.
- aws ec2 target --> aws ec2 instance id, `--aws_ec2_target` becomes `--aws-ec2-instance-id`
- aws ec2 connect --> aws ec2 instance connect (the technology is called "ec2 instance connect", not "ec2 connect", we can't be calling it different than aws calls it) `--aws-ec2-connect` becomes `--aws-ec2-instance-connect`
- https://mysocket.atlassian.net/browse/ME-1718
Tested locally:
```
Adrianos-MacBook-Pro:~ adriano$ AWS_PROFILE=default AWS_REGION=us-east-1 border0 socket connect demo-ec2-ic-socket --aws-ec2-instance-connect --aws-ec2-instance-id i-07ef34b7a4d50bb47 --host 44.203.135.224 --port 22
demo-ec2-ic-socket - ssh://demo-ec2-ic-socket-docs0.border0.io …
```
> [ME-1718] Proper AWS-nomenclature for ec2 instance connect

- internal/ssh/proxy.go
Re-establish compatibility of ec2 SSM targets with connector v2
- https://mysocket.atlassian.net/browse/ME-1718
```
Adrianos-MacBook-Pro:~ adriano$ AWS_PROFILE=default border0 connector start --v2
{"level":"info","ts":"2023-07-18T21:44:24-06:00","msg":"starting the connector service"}
{"level":"info","ts":"2023-07-18T21:44:24-06:00","msg":"connecting to connector server","server":"capi.staging.border0.com:443"}
{"level":"info","ts":"2023-07-18T21:44:24-06:00","msg":"new plugin","plugin":"875bfcfc-fe4f-4a5d-ba6b-a37516c39200"}
{"level":"info","ts":"2023-07-18T21:44:24-06:00","msg":"new socket","socket":"5c0bab4a-9fe0-4b4c-9d50-3826657bc2dc"}
{"level":"debug","ts":"2023-07-18T21:44:28-06:00","msg":"discovery result","plugin_id":"875bfcfc-fe4f-4a5d-ba6b-a37516c39200","discover …
```
> [ME-1718] Re-establish compatibility with connector v2

- cmd/connect.go
- cmd/run.go
- cmd/socket.go
- cmd/tunnel.go
- internal/api/api.go
- internal/http/handler.go
When we moved to border0 Listen functions we removed the old refresh job.
But the new refresh job was not added.
This PR will start the new refresh job.
Fixes # ME-1716
Tested locally with socket connect, run and connector mode.
> fix(ME-1716): start refresh token job before starting tunnel

- go.mod
- go.sum
- internal/connector_v2/cmds/builder.go
- internal/connector_v2/service.go
- Updates border0 go types lib to latest version
- First stab at implementing a connector metadata service
- https://mysocket.atlassian.net/browse/ME-1739
Tested in EC2
[ME-1739]: https://mysocket.atlassian.net/browse/ME-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1739] Connector Metadata Service First Stab

- go.mod
- go.sum
- internal/connector_v2/service.go
- internal/connector_v2/util/util.go
Sends collected connector metadata upstream to the api for updating
- https://mysocket.atlassian.net/browse/ME-1739
Tested against a local border0 api and checked the results in the db looked as expected.
[ME-1739]: https://mysocket.atlassian.net/browse/ME-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1739] Send Connector (v2) Metadata Upstream

- cmd/connector.go
- internal/connector_v2/border0_grpc_tunnel_credentials.go
- internal/connector_v2/config/config.go
- internal/connector_v2/service.go
After the recent changes to the grpc server side we can use border0 admin access tokens (and user tokens) to connect connectors (if the role policy is right). In cases where the credentials used are not a connector (v2) token -- the connector id needs to be provided explicitly
This adds a hidden flag to do that, as well as cleans up the existing GRPC authentication code.
- https://github.com/mysocketio/api/pull/971
This has been tested extensively. The details of such testing are in the corresponding api change PR: 
[ME-1761]: https://mysocket.atlassian.net/browse/ME-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1761] Proper GRPC Authentication

- cmd/client.go
- cmd/client/vpn/vpn.go
- cmd/root.go
- cmd/socket.go
- go.mod
- go.sum
- internal/ssh/proxy.go
- internal/vpnlib/vpnlib.go
Example:
```
17:15 $ sudo border0 socket connect vpn vpn-socket --client-ip 10.42.0.2 --server-ip 10.42.0.1 --route 100.0.0.1/32
vpn-socket - tls://vpn-socket-adriano.border0.io
=======================================================
Logs
=======================================================
{"level":"info","ts":"2023-07-28T17:15:53-07:00","msg":"Created TUN interface","interface_name":"utun3"}
```
```
17:05 $ sudo border0 client vpn
? choose a host: vpn-socket-adriano.border0.io []
{"level":"info","ts":"2023-07-28T17:06:10-07:00","msg":"Created TUN interface","interface_name":"utun4"}
{"level":"info","ts":"2023-07-28T17:06:10-07:00","msg":"Received control message","control_message":{"client_ip":"10.42.0.2","server_ip":"10.42.0.1","subnet_length":30,"routes":["100 …
```
> [MISC] Border0 VPN Implementation Over TLS

- internal/connector_v2/upstreamdata/builder.go
- internal/ssh/proxy.go
- send the client error logs to connector portal
- setup the target hostname and port when the auth method is border0 certificate
> [ME-1752] send connector logs to portal

- cmd/client/vpn/vpn.go
- cmd/root.go
- cmd/socket.go
- internal/vpnlib/connmap.go
- internal/vpnlib/ippool.go
- internal/vpnlib/iputil.go
- internal/vpnlib/vpnlib.go
VPN multiple-clients support. Create a TLS socket and then connect:
`sudo border0socket connect vpn  awsvpn --route 1.2.3.4/32 --vpn-subnet 10.42.0.0/22`
as a client to connect
`sudo border0-cli client vpn`
N/A -  experimental
Tested extensively manually
> [MISC] Support for Multiple VPN Clients

- internal/connector/discover/k8.go
Add `https` to k8s `border0.com/socketType` annotation, and set socket upstream type as `https` accordingly.
> add https socket type to k8s to set upstream type as https

- cmd/client.go
- cmd/client/httpproxy/httpproxy.go
- cmd/client/tls/tls.go
- cmd/root.go
- cmd/socket.go
- go.mod
- go.sum
- internal/http/server.go
- internal/httpproxylib/proxylib.go
Support for HTTP proxy over TLS socket
on the server:
`border0 socket connect proxy proxysocket`  start proxy
optionally add one or more `--allowed-host` to limit what is allowed to be proxied. If ommited, all urls are allowed to proxied
on the client `./border0 client proxy  -c 2` This will start two upstream client connections, over which HTTP requests to the proxy will be load balanced.  default is one stream. More streams allow for better throughput if there are multiple parallel requests.
optionally use `./border0 client proxy  -t` for a terminal UI (TUI), experiment.
Ater that you can use localhost as proxy, for example test with curl:
```
$ curl   -x http://127.0.0.1:8080 https://ifconfig.io
207.102.57.34
```
Please describe the tests that you ran to verify your …
> ME-1786 Forward http proxy

- lib/varsource/README.md
- lib/varsource/variable_source.go
- lib/varsource/variable_source_multiple_upstream.go
- lib/varsource/variable_upstream_file.go
Better handling of upstream variables. No longer use dollar bracket syntax (e.g. `${...}`) in favour of using `from:PREFIX...` (which can be escaped with `\from`.
- https://mysocket.atlassian.net/browse/ME-1787
With the following example program:
```
package main
import (
"context"
"fmt"
"log"
"github.com/borderzero/border0-cli/lib/varsource"
)
func main() {
vs := varsource.NewDefaultVariableSource()
vars, err := vs.GetVariables(context.Background(), map[string]string{
"DB_USERNAME": "from:env:DB_USERNAME",
"DB_PASSWORD": "from:file:~/.creds/password.txt",
})
if err != nil {
log.Fatalf("failed to get variables: %v", err)
}
for key, value := range vars {
fmt.Println(fmt.Sprintf("%s : %s", key, value))
}
}
```
Ran:
```
✔ ~/go/src/github.com/borderzero/border0-cli …
```
> [ME-1787] VarSource Path Change

- cmd/client/httpproxy/httpproxy.go
- cmd/client/vpn/vpn.go
- cmd/login.go
- internal/client/resources.go
- internal/http/handler.go
- internal/vpnlib/vpnlib.go
This change implements some of the user feedback regarding the VPN log messages and  HTTP proxy crash.
Also making sure the user can use sudo without losing his or her preferences, ie we use the original users preference, admin and client token locations.
> ME-1788 Fix Sudo behaviour with border0 cli

- internal/vpnlib/vpnlib.go
Fix to make sure we read the complete first 2 bytes io.ReadFull() Previously, we were using conn.Read(headerBuffer), and even though the buffer size was 2 bytes, sometimes we ended up with 1 byte, which caused us to determine the wrong size of the subsequent payload data.
> ME-1791 Fix VPN header read

- go.mod
- go.sum
- internal/connector_v2/service.go
- internal/connector_v2/upstreamdata/builder.go
- Support for the built in ssh server in connector v2 (based on the new upstream connection type defined in the border0 go sdk)
- A minor refactor that shortens the code quite a bit by using a `set` library instead of iterating over slice
- https://mysocket.atlassian.net/browse/ME-1801
In the staging border0 environment with a new connector. Manually inserted the socket upstream config into the db.
```
16:44 $ ./border0 connector start --v2
{"level":"info","ts":"2023-08-08T16:45:25-07:00","msg":"starting the connector service"}
{"level":"info","ts":"2023-08-08T16:45:25-07:00","msg":"connecting to connector server","server":"capi.staging.border0.com:443"}
{"level":"debug","ts":"2023-08-08T16:45:25-07:00","msg":"collected connector metadata","metadata":{}} …
```
> [ME-1801] Connector V2 Built-In SSH Server Support

- Makefile
Add `-s` and `-w` linker flags to strip debugging info and reduce binary size.
Before:
After:
Manually tested with `make build-all`.
> ME-1804: strip go debugging info from binary with linker flags

- cmd/client/vpn/vpn.go
- go.sum
- internal/vpnlib/iputil.go
A fix to make sure we only take into account network interfaces that are up. And we need to make sure it doesn't match the newly created VPN interfaces.
This broke my blenz coffee shop test! Now i can vpn again from coffeeshop.
> ME-1788 Fix for local route lookups

- cmd/completion.go
- internal/command/command.go
Commands on macOS should not show brew error when it's not installed.
Manually tested on macOS with and without brew installed.
> ME-1717: fix brew error when running commands on macos

- Makefile
Add new build target for Linux 32bit OSes.
Manually tested with `make build-all` and tested the build in a 32bit Debian Linux.
> ME-1805: add new build target for linux 386

- internal/service_daemon/common.go
- internal/service_daemon/service_daemon.go
Introduced a build-breaking change for openbsd in https://github.com/borderzero/border0-cli/pull/152
N/A
N/A
[ME-1808]: https://mysocket.atlassian.net/browse/ME-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1808] Service Daemon Compatibility with OpenBSD

- internal/service_daemon/common.go
- internal/service_daemon/service_daemon.go
- internal/service_daemon/service_daemon_openbsd.go
Introduced a build-breaking change for openbsd in https://github.com/borderzero/border0-cli/pull/152
The previous fix did not work.
N/A
N/A
[ME-1808]: https://mysocket.atlassian.net/browse/ME-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1808] Fix OpenBSD Build

- internal/connector_v2/config/config.go
Ignore error when HOME directory is not defined.
In EC2:
```
[   15.123908] cloud-init[1553]: + sudo chmod +x /usr/local/bin/border0
[   15.209225] cloud-init[1553]: + export AWS_REGION=us-east-1
[   15.211599] cloud-init[1553]: + AWS_REGION=us-east-1
[   15.212308] cloud-init[1553]: + export BORDER0_TOKEN=from:aws:ssm:connector-my-connector-token
[   15.213429] cloud-init[1553]: + BORDER0_TOKEN=from:aws:ssm:connector-my-connector-token
[   15.214438] cloud-init[1553]: + export BORDER0_TUNNEL=tunnel.border0.com
[   15.215269] cloud-init[1553]: + BORDER0_TUNNEL=tunnel.border0.com
[   15.216040] cloud-init[1553]: + export BORDER0_CONNECTOR_SERVER=capi.border0.com:443
[   15.216991] cloud-init[1553]: + BORDER0_CONNECTOR_SERVER=capi.border0.com:443
[   15.217886] cloud-init[1553]: + export …
```
> [HOTFIX] Dont break connector v2 when HOME not defined

- internal/connector_v2/service.go
- internal/connector_v2/upstreamdata/builder.go
- internal/ssh/server.go
Adds options to the built in ssh server constructor to override the username.
- part of https://mysocket.atlassian.net/browse/ME-1801
[ME-1801]: https://mysocket.atlassian.net/browse/ME-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1801] Allow Overriding SSH Username In Built-In SSH Server

- cmd/connect.go
- cmd/root.go
- cmd/socket.go
- internal/api/models/socket.go
- internal/connector/discover/k8.go
- internal/connector/discover/static_sockets.go
Legacy connectors can get in an update loop because if you set the SNI header in the portal and the local config file doesn't have the same upstream http hostname, it will try to set empty string as the hostname when it sees the mismatch. The CLI does not include hostname in the socket request if it is empty string; after this change it will.
- https://mysocket.atlassian.net/browse/ME-1816
Locally against latest API
[ME-1816]: https://mysocket.atlassian.net/browse/ME-1816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1816] Allow Empty Hostname

- internal/ssh/server.go
- internal/ssh/server_unix.go
- internal/ssh/server_windows.go
Basically, the shell still tries to force the login to be the name provided in the ssh session even if there is an override, this changes that.
- https://mysocket.atlassian.net/browse/ME-1842
Tested against real built-in-ssh sockets in staging
[ME-1842]: https://mysocket.atlassian.net/browse/ME-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1842] Fix username mismatch problem in built-in-ssh

- internal/connector_v2/service.go
Trying to use human credentials does not work (client side)...
```
✔ ~/go/src/github.com/mysocketio/api [ME-1821|✔]
09:45 $ BORDER0_TOKEN=$(cat ~/.border0/token) border0 connector start --v2 --connector-id 33a117bf-7faa-412d-be97-fa5e1d63f811
{"level":"info","ts":"2023-08-15T09:45:25-07:00","msg":"starting the connector service"}
{"level":"info","ts":"2023-08-15T09:45:25-07:00","msg":"connecting to connector server","server":"capi.border0.com:443"}
{"level":"debug","ts":"2023-08-15T09:45:25-07:00","msg":"collected connector metadata","metadata":{}}
{"level":"info","ts":"2023-08-15T09:45:26-07:00","msg":"new socket","socket":"3d99a685-3ab8-44be-837d-e9d21a7b5e85"}
2023/08/15 09:45:26 border0 listener: failed to get userid from token: failed to parse token
2023/08/15 09:45:26 border0 …
```
> [ME-1845] Fix Human Auth With Connector V2

- internal/api/api.go
- internal/api/models/connector.go
- internal/connector_v2/install/common.go
- part of https://mysocket.atlassian.net/browse/ME-1821
Tested the installer locally against the production API
[ME-1821]: https://mysocket.atlassian.net/browse/ME-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1821] Enable Built In SSH Server During Connector Install

- internal/api/api.go
- internal/api/models/connector.go
- internal/connector_v2/install/aws.go
- internal/connector_v2/install/common.go
Simplify the cloud installer by no longer prompting for name (we'll just get an available one, which the customer can change later on anyways).
- https://mysocket.atlassian.net/browse/ME-1821
Tested the installer.
[ME-1821]: https://mysocket.atlassian.net/browse/ME-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1821] Simplify Connector Cloud Install By Assuming Name

- cmd/root.go
socket show displays address for upstream hostname:
HTTP Options:
```
┌───────────────┬───────────────────┐
│ UPSTREAM TYPE │ UPSTREAM HOSTNAME │
├───────────────┼───────────────────┤
│ http          │ 0x140005148c0     │
└───────────────┴───────────────────┘
```
Fixes # ((ME-1859)
Tested locally
> fix(ME-1859): socket show displays address for upstream hostname

- go.mod
- go.sum
- internal/connector_v2/upstreamdata/http.go
- internal/connector_v2/upstreamdata/tls.go
- vendor/github.com/borderzero/border0-go/lib/types/netaddr/ipv4.go
- vendor/github.com/borderzero/border0-go/lib/types/null/null.go
- vendor/github.com/borderzero/border0-go/lib/types/regex/regex.go
- vendor/github.com/borderzero/border0-go/lib/types/slice/slice.go
- vendor/github.com/borderzero/border0-go/types/common/aws.go
- vendor/github.com/borderzero/border0-go/types/connector/plugin.go
- vendor/github.com/borderzero/border0-go/types/service/common.go
- vendor/github.com/borderzero/border0-go/types/service/configuration.go
- vendor/github.com/borderzero/border0-go/types/service/database_service_configuration.go
- vendor/github.com/borderzero/border0-go/types/service/http_service_configuration.go
- vendor/github.com/borderzero/border0-go/types/service/ssh_service_configuration.go
- vendor/github.com/borderzero/border0-go/types/service/tls_service_configuration.go
- vendor/modules.txt
Introduces support for basic http and tls services with connector v2. Note that the config will need to change to allow for the built-in http webserver and its configuration.
- part of https://mysocket.atlassian.net/browse/ME-1854
Locally with an http socket manually written to the staging db
[ME-1854]: https://mysocket.atlassian.net/browse/ME-1854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1854] Initial Support for HTTP and TLS Sockets in Connector V2

- cmd/connector.go
- internal/connector_v2/install/local.go
- internal/service_daemon/common.go
Fixes a bug where the connector cannot be uninstalled when the service is stopped.
- https://mysocket.atlassian.net/browse/ME-1881
Tested uninstalling with a stopped service
[ME-1881]: https://mysocket.atlassian.net/browse/ME-1881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1881] Fix: Uninstall When Service Stopped

- .github/workflows/build_and_release_rpm_repo.yml
- .gitignore
- CENTOS/post-install.sh
- CENTOS/post-uninstall.sh
- build-rpm.sh
- create-rpm-builder.sh
Final touches for the RPM build logic
fix for docker: process the input device is not a TTY
manually from a branch
https://github.com/borderzero/border0-cli/actions/runs/5953845165/job/16149048153
https://github.com/borderzero/border0-cli/actions/runs/5954074296
> ME-1867: Centos9 Docker based worker for RPM build GH Action

- generate-rpm-repo.sh
We have forgotten to sign the RPM repo
```
root@b0-opensuse-15:/# sudo zypper refresh
Warning: File 'repomd.xml' from repository 'border0-repo' is unsigned.
Note: Signing data enables the recipient to verify that no modifications occurred after the data
were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
and in extreme cases even to a system compromise.
Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
whole repo.
Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
anymore! You should not continue unless you know it's safe.
File 'repomd.xml' from repository 'border0-repo' is unsigned, continue? [yes/no] (no): yes
```
tested on suse
> ME-1776: adding the PGP signing for RPM repo

- internal/api/models/socket.go
- internal/connector_v2/upstreamdata/ssh.go
- internal/sqlauthproxy/handler.go
- internal/sqlauthproxy/mysql.go
- internal/sqlauthproxy/postgres.go
- internal/ssh/proxy.go
- internal/util/awsconfig.go
Currently, we support overriding AWS credentials for SSM and EC2 Instance Connect (ssh sockets). But we don't pay attention to those credentials in the CLI. 
This change introduces making use of any given AWS credentials.
- https://mysocket.atlassian.net/browse/ME-1872
This has been thoroughly tested against live sockets by providing static credentials.
[ME-1872]: https://mysocket.atlassian.net/browse/ME-1872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1872] Handle Static AWS Credentials for Connector V2

- lib/varsource/utils.go
- lib/varsource/variable_source.go
- lib/varsource/variable_upstream_aws_secretsmanager.go
- lib/varsource/variable_upstream_aws_ssm.go
Need to be able to set the region to get an ssm parameter from a different aws region
- https://mysocket.atlassian.net/browse/ME-1900
Tested locally overriding my token's location with:
```
BORDER0_TOKEN=from:aws:ssm:cool-token,aws_region=us-west-2,aws_profile=dev ./border0 connector start --v2
```
[ME-1900]: https://mysocket.atlassian.net/browse/ME-1900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1900] Overrides Support in VarSource library

- internal/connector_v2/install/aws_cfn_template.go
Adds the IAM permissions for connector instance to generate temporary user credentials for RDS DBs.
- https://mysocket.atlassian.net/browse/ME-1905
This was tested against a live AWS environment.
[ME-1905]: https://mysocket.atlassian.net/browse/ME-1905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1905] Add RDS DB Connect Permissions To Connector V2 CFN

- internal/connector_v2/upstreamdata/tls.go
Handle sockets with TLS config in connector v2.
Will tackle HTTP proxy and VPN types separately -- that work is WIP in a different branch.
- https://mysocket.atlassian.net/browse/ME-1828
Tested locally with a TLS socket.
[ME-1828]: https://mysocket.atlassian.net/browse/ME-1828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1828] Handle TLS Sockets in Connector V2

- internal/sqlauthproxy/postgres.go
Even worse than not handling it well is that the error log printed to stdout includes the whole URL...
> This database has been killed - the password below get's ya nothing
```
{"msg":"sql proxy failed","socket_id":"08768891-b309-420a-b753-cc29be4b1710","error":"sqlauthproxy: cannot parse `postgres://postgres:xxxxxx@[[OBFUSCATED_RDS_IDENTIFIER]].us-east-1.rds.amazonaws.com:5432?sslmode=prefer`: failed to parse as URL (parse \"postgres://postgres:[+}[&8wiEaoB%GOMGR]8AyL(b7M2@[[OBFUSCATED_RDS_IDENTIFIER]].us-east-1.rds.amazonaws.com:5432?sslmode=prefer\": net/url: invalid userinfo)"}
```
We use the library https://github.com/jackc/pgconn, similar issue for not handling special characters was opened here https://github.com/jackc/pgconn/issues/18, suggested workaround/fix is to url encode the …
> [ME-1927] SQL Proxy Can't Handle Special Chars in Username/Password

- cmd/client/tls/tls.go
- internal/client/client.go
use outer tls connection for connectorAuth and inner tls connection for e2e encryption.
Fixes # (ME-1894)
Tested locally
> fix(ME-1894): use outer tls connection for connectorAuth and inner tls connection for e2e encryption

- .github/workflows/build_and_release.yml
- .github/workflows/run_tests.yml
- Dockerfile
- Makefile
Run build and release jobs in parallel from:
- github action workflow `build_and_release.yml` so it builds for all platform combinations in different VMs
- `Makefile` jobs like `make build-all` now can be run with `-j` option as `make build-all -j`
Manually tested with `Makefile` and github actions
> ME-1938: run build and release jobs in parallel

- Makefile
Fix broken rpm and deb build since `BINARY_NAME` was changed from `mysocketctl` to `border0`
Manually tested with `make build`
> ME-1938: fix rpm and deb build

- .github/workflows/build_and_release.yml
- build-deb.sh
- build-rpm.sh
Fix broken rpm and deb build since `BINARY_NAME` was changed from `mysocketctl` to `border0`
Manually tested with triggering github action workflow.
> ME-1938: fix another error from rpm and deb build

- go.mod
- go.sum
- internal/connector_v2/upstreamdata/database.go
- vendor/github.com/aws/session-manager-plugin/src/sessionmanagerplugin/session/session.go
- vendor/github.com/borderzero/border0-go/types/service/database_service_configuration.go
- vendor/modules.txt
Change upstream database config names:
- Change AWS RDS IAM auth `AwsRegion` to `RdsInstanceRegion`
- Change AWS RDS IAM auth `AwsCredentials` to pointer/optional
Manually tested
> ME-1915: change database config names

- internal/connector_v2/install/aws_cfn_template.go
Migrate LaunchConfiguration to LaunchTemplate (because LaunchConfiguration is deprecating), see https://docs.aws.amazon.com/autoscaling/ec2/userguide/migrate-to-launch-templates.html.
- https://mysocket.atlassian.net/browse/ME-1942
The connector installer with the new template has been tested.
[ME-1942]: https://mysocket.atlassian.net/browse/ME-1942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1942] Migrate LaunchConfiguration to LaunchTemplate (cfn)

- CENTOS/post-install.sh
- DEBIAN/postinst
- cmd/connector.go
- internal/connector_v2/config/config.go
- internal/connector_v2/install/aws_cfn_template.go
- internal/connector_v2/install/local.go
- https://mysocket.atlassian.net/browse/ME-1877
With the following **valid** config in the right place:
<details>
```
11:33 $ cat /etc/border0/border0.yaml
connector:
name: "my-awesome-connector"
aws-region: "us-east-1"
credentials:
token: [[ HIDDEN TOKEN ]]
sockets:
- ssh-connector-lab:
port: 22
host: 127.0.0.1
type: ssh
sshserver: true
```
</details>
```
✔ ~/go/src/github.com/borderzero/border0-cli [ME-1877_v2_installer_as_default|✔]
11:31 $ AWS_PROFILE=demo BORDER0_LOG_LEVEL=debug BORDER0_TOKEN=$(cat ~/.border0/token) ./border0 connector start --connector-id 8f31bb64-6077-4540-b031-2b907d44ef9d
{"level":"info","ts":"2023-09-06T11:31:59-07:00","msg":"using …
```
> [ME-1877] Infer Connector Version In Start/Install, Expose V2

- internal/border0/socket.go
- internal/connector_v2/service.go
- internal/ssh/server.go
add config hash to avoid socket restarts
Fixes # (ME-1949)
Tested locally
> fix(ME-1949): add config hash to avoid socket restarts

- cmd/connector.go
- internal/api/api.go
- internal/api/models/connector.go
- internal/connector_v2/install/aws.go
- Fixes `border0 connector status` in `OS=darwin` (MacOS), which was trying to run `systemctl` (wrong tool for OS)
- Enables AWS Discovery Plugins during the AWS Connector Installer
```
... output before ommitted
🚀 Border0 connector "aws-connector-2" created successfully!
🚀 Border0 connector plugin "aws_ec2_discovery" enabled successfully!
🚀 Border0 connector plugin "aws_ecs_discovery" enabled successfully!
🚀 Border0 connector plugin "aws_rds_discovery" enabled successfully!
🚀 Border0 connector token "border0-aws-connector-1694459528" created successfully!
🚀 SSM Parameter "border0-aws-connector-2-token-1" created successfully!
🚀 CloudFormation stack "border0-aws-connector-1694459528" creation initiated, events below:
... output after ommitted
```
- …
> [ME-1965] [ME-1966] Various Connector Installer Improvements

- internal/api/api.go
- internal/http/handler.go
There's a bug where the home directory is not properly determined when running with `sudo`.
- https://mysocket.atlassian.net/browse/ME-1964
This was tested on amazon linux 2023 and ubuntu machines on ec2
[ME-1964]: https://mysocket.atlassian.net/browse/ME-1964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1964] Fix Connector Install on Linux

- internal/service_daemon/common.go
The message that we check for to determine whether the system is installed is different for windows... so the installation fails.
- https://mysocket.atlassian.net/browse/ME-1982
On a windows machine in the office. The installer still fails at a later stage but this time because we are running a non-release version of the software (potentially, as per stack overflow).
[ME-1982]: https://mysocket.atlassian.net/browse/ME-1982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1982] Fix Connector Installer on Windows

- cmd/socket.go
- internal/border0/socket.go
if socket has upstream username in db/api, use it when creating the local ssh server
Manually tested with:
```shell
border0 socket create --name test-ssh-username --type ssh --upstream_username rollie
border0 socket connect test-ssh-username --sshserver
```
And then log into my SSH socket.
> use socket upstream username in local ssh server

- cmd/child.go
- internal/process/common.go
- internal/process/setup.go
- internal/process/setup_windows.go
- Abstracts away platform specific code for SFTP process management (setting uid, gid, groups)
- Hides the `child` command tree so that it isnt invoked manually by curious customers
- Fixes the broken CLI build due to syscall package compilation failures on Windows
- https://mysocket.atlassian.net/browse/ME-1981
The build succeeds -- more testing can be done later.
[ME-1981]: https://mysocket.atlassian.net/browse/ME-1981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1981] Abstract Platform Specific SFTP Logic, Hide "child" Command Tree

- go.mod
- go.sum
- vendor/github.com/aws/session-manager-plugin/src/sessionmanagerplugin/session/session.go
- vendor/github.com/borderzero/discovery/discoverers/discoverer_network.go
- vendor/github.com/borderzero/discovery/resource.go
- vendor/modules.txt
No-Code change to support discovering networked rdp and vnc servers in connector v2.
`go get -u github.com/borderzero/discovery && go mod tidy && go mod vendor`
- https://mysocket.atlassian.net/browse/ME-2012
This was tested locally by running this modified CLI against the production Border0 API and seeing the results in the portal.
[ME-2012]: https://mysocket.atlassian.net/browse/ME-2012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2012] Upgrade Discovery Lib For RDP & VNC Support

- cmd/connector.go
- internal/connector/service.go
This does nothing other than print a misleading message...
- https://mysocket.atlassian.net/browse/ME-1982
N/A
[ME-1982]: https://mysocket.atlassian.net/browse/ME-1982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1982] Remove UnImplemented Connector Stop Command

- internal/ssh/server_unix.go
Add small sleep before starting io.Copy. This was removed in the last PR.
fix: ME-1981
Tested using ec2 instance.
> fix: add sleep again

- internal/api/models/socket.go
- internal/connector_v2/upstreamdata/ssh.go
- internal/ssh/proxy.go
Future-proof the border0 certificate username option.
- https://mysocket.atlassian.net/browse/ME-2065
This has been tested with border0 certificate sockets with connector v2.
[ME-2065]: https://mysocket.atlassian.net/browse/ME-2065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2065] Future-proof Border0 Certificate Username

- cmd/login.go
- cmd/root.go
- go.mod
- go.sum
- vendor/github.com/mdp/qrterminal/.travis.yml
- vendor/github.com/mdp/qrterminal/CHANGELOG.md
- vendor/github.com/mdp/qrterminal/README.md
- vendor/github.com/mdp/qrterminal/qrterminal.go
- vendor/modules.txt
- vendor/rsc.io/qr/LICENSE
- vendor/rsc.io/qr/README.md
- vendor/rsc.io/qr/coding/qr.go
- vendor/rsc.io/qr/gf256/gf256.go
- vendor/rsc.io/qr/png.go
- vendor/rsc.io/qr/qr.go
Adds a hidden (for now) flag `--qr` to the `border0 login` command to print a QR code to stdout to scan with a mobile device in order to authenticate a device/computer with any QR reader (e.g. mobile phone).
The behaviour without the flag is completely unchanged -- this is all net new.
- N/A
Tested locally with and without the `--qr` flag.
> [MISC] Add --qr flag to login command

- internal/api/api.go
- internal/api/models/connector.go
- internal/connector_v2/install/aws.go
- internal/connector_v2/install/common.go
- internal/connector_v2/install/local.go
Sets the username of the built-in ssh server to SUDO_USER if present during installation (for local installer locally).
- https://mysocket.atlassian.net/browse/ME-2083
Tested a local and an aws installation.
[ME-2083]: https://mysocket.atlassian.net/browse/ME-2083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2083] Set connector user to SUDO_USER if present

- internal/connector_v2/upstreamdata/top_level.go
I was trying to use upstream variables in parameter store in an AWS-installer-based connector and it didnt work, I had to get on the box and start a new connector to get the log locally:
```
error evaluating variable from:aws:ssm:/demo/mysql-db-password: failed to get value for variable definition "aws:ssm:/demo/mysql-db-password": failed to get ssm parameter "/demo/mysql-db-password": operation error SSM: GetParameter, https response error StatusCode: 400, RequestID: 006a388f-65ce-4fe4-99b8-a425c676e9a4, api error AccessDeniedException: User: arn:aws:sts::[[HIDDEN-ACCOUNT]]:assumed-role/border0-aws-connector-169582-ConnectorInstanceRole-9WAMQWJ2HHGC/i-031796992a1755b0d is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:[[HIDDEN-ACCOUNT]]:parameter/demo/mysql …
```
> [ME-2102] Propagate Upstream Variable Fetch Errors

- cmd/connector.go
- internal/connector_v2/install/aws_cfn_template.go
Ssm parameters can begin with a slash character (`/`). When they do, the slash must be ommitted from the resource ARN in IAM policies that reference them. This takes care of that.
- https://mysocket.atlassian.net/browse/ME-2115
Ran the installer with tokens stored in each of:
- a path without a '/' as the first character
- a path with a `/` as the first character
[ME-2115]: https://mysocket.atlassian.net/browse/ME-2115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2115] Handle Border0 Token SSM Params With Slash

- cmd/version.go
This fixes the issue where /tmp and the location of border0 cli are on different partitions.
then a simple rename doesnt work and you see something like
```
sh-5.2$ sudo border0 version upgrade
Upgrading /usr/local/bin/border0 to version v1.1-496-gc91658e
2023/09/28 16:38:51 rename /tmp/border0-v1.1-496-gc91658e1883797401 /usr/local/bin/border0: invalid cross-device link
```
Fixes # ME-2116 
> ME-2116 fix for upgrading border0 cli between partitions

- internal/connector_v2/install/aws.go
- internal/connector_v2/install/common.go
- internal/connector_v2/install/local.go
- internal/http/handler.go
Limit the length of the token name so that it doesnt break the http request.
- https://mysocket.atlassian.net/browse/ME-2226
Installing the connector locally and on AWS with the new code
[ME-2226]: https://mysocket.atlassian.net/browse/ME-2226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2226] Limit Length of Connector Token Name in Installers

- cmd/login.go
Programmatic basic login is no longer allowed.
- https://mysocket.atlassian.net/browse/ME-2233
N/A just hiding the flags. Testing they still work.
[ME-2233]: https://mysocket.atlassian.net/browse/ME-2233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2233] Hide email and password flags for admin login

- internal/util/hostkey.go
The bug is we try to create the directory if `err == nil`, instead we should try to create the directory if `err != nil` (and more specifically if `os.IsNotExist(err)`.
- https://mysocket.atlassian.net/browse/ME-2216
N/A still mostly an experimental feature that there is no way to opt-in or opt-out of and is fully API-controlled. No customers are affected by this code change.
[ME-2216]: https://mysocket.atlassian.net/browse/ME-2216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2216] Fix Hostkey Directory Existence Check Bug

- internal/vpnlib/ippool.go
- internal/vpnlib/iputil.go
Prevent users from providing  `--vpn-subnet 0.0.0.0/0` as that may, on some systems, exhaust memory. For now, a hard limit to a /16 max, which should be more than sufficient
```
$ sudo ./border0-cli socket connect vpn myvpn  --vpn-subnet 0.0.0.0/0 --route 172.16.0.0/24
myvpn - tls://myvpn-border0-demo.border0.io
=======================================================
Logs
=======================================================
2023/11/13 12:42:12 Failed to create IP Pool: invalid cidr range, VPN subnet size to large. Cannot be more than a /16), got 0.0.0.0/0
```
Please describe the tests that you ran to verify your changes. Provide …
> ME-2287 prevent large vpn subnet size

- cmd/policy.go
- cmd/root.go
- internal/api/models/policy.go
Policy tester option in CLI 
```
$ ./border0-cli policy test --name orgwide --email andree@border0.com --ip 206.214.246.9
Testing Policy: orgwide 8ebbcd53-bea4-4d8c-b3d9-80d35cfe2e99
✅ Policy Passed!
policy: "orgwide", Email address matched policy (andree@border0.com)
policy: "orgwide", IP address matched policy (206.214.246.96)
policy: "orgwide", Country code matched policy (CA)
policy: "orgwide", Date window matched policy (2023-11-15T06:36:21Z)
policy: "orgwide", Time window matched policy (06:36)
The following actions would be allowed:
{
"http": [
"*"
],
"ssh": [
"*"
],
"tls": [
"*"
]
}
```
```
$ ./border0-cli policy test --name orgwide --email andree@bla.xom --ip 1.2.3.4
Testing Policy: orgwide 8ebbcd53-bea4-4d8c-b3d9-80d35cfe2e99
⛔ Policy Failed
policy: "orgwide", Email address …
```
> ME-2300 Policy tester in cli

- .github/codeql/codeql-config.yml
- .github/workflows/build_and_release.yml
- .github/workflows/codeql.yml
- We want to roll out things quicker... and it seems github is limiting our bandwidth, so we will check out the code just once
- Also adds codeql config to exclude /vendor
[ME-2318]: https://mysocket.atlassian.net/browse/ME-2318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2318] Adjust GitHub Workflows

- .github/workflows/build_and_release.yml
We are downloading the code once per platform, this changes it to do it just once, and pass it to the N platform-specific builds via the cache. The cache key is the workflow run id (unique per workflow execution).
We do this because github will throttle network bandwidth if a workflow downloads too much data. If we download the repo 10 times we've seen our download speed go from 30+ Mbps to 150 Kbps
- https://mysocket.atlassian.net/browse/ME-2318
Triggered a Build and Release job from this branch.
[ME-2318]: https://mysocket.atlassian.net/browse/ME-2318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2318] Checkout Code Just Once for Build+Release

- cmd/login.go
- internal/http/handler.go
Improves the logic for retries with the OAuth2 Device Authorization Flow. Done as a result of suggestions from @steiler in https://github.com/srl-labs/containerlab/pull/1768
- https://mysocket.atlassian.net/browse/ME-2365
Tested building the CLI locally and logging in.
[ME-2365]: https://mysocket.atlassian.net/browse/ME-2365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2365] Improved Device Auth Code Retry Logic

- internal/connector_v2/plugin/builder.go
- internal/connector_v2/plugin/plugin.go
Handle AWS EKS discoverer requests from the API in the connector.
- https://mysocket.atlassian.net/browse/ME-2373
Ran the modified connector code locally and created an AWS EKS discovery plugin via the API and saw the connector act as expected.
[ME-2373]: https://mysocket.atlassian.net/browse/ME-2373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2373] Handle Initialization of AWS EKS Discovery Plugins

- internal/connector_v2/install/aws.go
- internal/connector_v2/install/aws_cfn_template.go
- internal/ssh/session/kubectl_exec_session.go
- Enable the EKS discovery plugin in the aws installer
- Fix a bug hardcoding region of eks cluster to eu-west-2
- Add IAM permissions for EKS to the AWS connector installer cfn stack template
- https://mysocket.atlassian.net/browse/ME-2388
Tested using the aws installer with the new template.
[ME-2388]: https://mysocket.atlassian.net/browse/ME-2388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2388] EKS Support in AWS Installer

- internal/ssh/config/config.go
- internal/ssh/proxy.go
- internal/ssh/session/docker_exec_session.go
- internal/ssh/session/kubectl_exec_session.go
- Support for docker exec sockets
- Fixes bug in kubectl exec upstream where the shell preference order during shell deduction is not maintained due to the use of sets
- https://mysocket.atlassian.net/browse/ME-2391
(tokens have been axed)
https://github.com/borderzero/border0-cli/assets/16856511/bb6fb154-8bf4-430a-b63f-175571c12439
This has been tested by hardcoding a kubectl exec socket to instead use the docker exec logic. It works well.
[ME-2391]: https://mysocket.atlassian.net/browse/ME-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2391] Docker Exec Socket Upstream Support

- internal/ssh/session/common/public_key_callback.go
- internal/ssh/session/common/recording.go
- internal/ssh/session/common/window_size.go
- internal/ssh/session/docker_exec_session.go
- internal/ssh/session/kubectl_exec_session.go
- internal/ssh/session/local_session.go
- internal/ssh/session/session.go
- internal/ssh/session/ssh_session.go
- internal/ssh/session/ssm_session.go
Extract generic public key callback handler code into a generic function to-be-shared by all implementations of the `SessionHandler` interface.
- https://mysocket.atlassian.net/browse/ME-2408
REFACTOR
Tested all socket types continue to operate normally with a modified version of the connector locally.
[ME-2408]: https://mysocket.atlassian.net/browse/ME-2408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2408] Abstract/Refactor E2EE PublicKeyCallback Handler

- cmd/socket.go
- internal/connector/core/core.go
- internal/connector_v2/service.go
- internal/util/certificate.go
fix(ME-2329): multiple fixes for reading/storing e2ee certificates
* fix: don't fail on reading connector cert as non root
* fix: use connectorID and orgID, was empty string
Fixes # (ME-2329)
- [ x Bug fix (non-breaking change which fixes an issue)
Tested with connector V2 and socket connect with root and non-root user.
> fix(ME-2329): multiple fixes for reading/storing e2ee certificates

- go.mod
- go.sum
- vendor/github.com/gliderlabs/ssh/circle.yml
- vendor/github.com/gliderlabs/ssh/context.go
- vendor/modules.txt
Patches for [[CVE-2023-48795](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-48795)].
See also:
- [CVE Publication from MITRE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-48795)
- [Researcher Notes](https://terrapin-attack.com/)
- [Researcher Tweet](https://twitter.com/TrueSkrillor/status/1736774389725565005)
- [Issue Against the Go(lang) Repo](https://github.com/golang/go/issues/64784)
- [Golang Maintainers' Official Announcement of the Release of `golang.org/x/crypto` v0.17.0, fixing the issue](https://groups.google.com/g/golang-announce/c/qA3XtxvMUyg/m/ZOwFpYq3AAAJ)
[ME-2412]: https://mysocket.atlassian.net/browse/ME-2412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2412] Bump github.com/gliderlabs/ssh

- go.mod
- go.sum
- internal/sqlauthproxy/mssql.go
- vendor/github.com/microsoft/go-mssqldb/proxy.go
- vendor/modules.txt
add tls mssql support
Fixes # (ME-2378)
tested in staging
> feat(ME-2378): add tls mssql support and  aws IAM auth and gcp cloudsql proxy support for sqlserver

- cmd/socket.go
- internal/connector/core/core.go
- internal/connector_v2/service.go
- internal/util/certificate.go
- internal/util/hostkey.go
fix hostkey and certificate reading/storing
Fixes # (ME-2495)
Tested locally with non existing certificates and hostkeys, with invalid certificates in both `socket connect` mode and connector mode.
> ME-2495: fix hostkey and certificate reading/storing

- cmd/client/vpn/vpn.go
- internal/vpnlib/iputil.go
- internal/vpnlib/vpnlib.go
I had previously removed  the DNS logic. But  as i'm now in a coffeeshop this broke my vpn.
Problem happens when you have 10.x.x.x.x DNS server, that doesnt sit in your local (directly connected) subnet. 
In that case with VPN, your DNS fails. So i added back some logic to detect that case and add bypass routes.
long term, we may wanna push a DNS server config.
> ME-2597-DNSFIX fixing DNS

- cmd/client.go
- cmd/client/rdp/rdp.go
- cmd/client/tls/tls.go
- cmd/client/utils/copy.go
- cmd/client/utils/local_proxy_and_client.go
- cmd/client/vnc/vnc.go
Just adding a couple of commands to make it easier to deal with vnc/rdp services behind vanilla TCP (a.k.a. TLS) sockets.
- https://mysocket.atlassian.net/browse/ME-2604
This has been tested locally for both VNC and RDP services.
[ME-2604]: https://mysocket.atlassian.net/browse/ME-2604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2604] Add 'border0 client vnc' and 'border0 client rdp' commands

- cmd/client/utils/local_proxy_and_client.go
- go.mod
- go.sum
- vendor/github.com/borderzero/water/syscalls_tun_windows.go
- vendor/modules.txt
- Uses released version of water fork (borderzero/water)
- Fixes bug in rdp client opening for non macos
- https://mysocket.atlassian.net/browse/ME-2604
Tested locally on a windows machine and a mac.
[ME-2604]: https://mysocket.atlassian.net/browse/ME-2604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2604] Various Improvements

- cmd/client/tls/tls.go
- cmd/client/utils/copy.go
- cmd/client/utils/local_proxy_and_client.go
We think that using buffered reader/writers breaks `border0 client tls` for the raw SSH client flow.
> [ME-2604] Revert vnc/rdp refactor code changes

- cmd/client/rdp/rdp.go
- cmd/client/utils/local_proxy_and_client.go
- cmd/client/vnc/vnc.go
will allocate a port dynamically, so users doesn't have to (but still can) provide a listener port
so you can just type in border0 client rdp and select the socket
> ME-2632 Dynamic Port allocation for RDP and VNC

- go.mod
- internal/ssh/server/server_unix.go
don't use login cmd if no pty is requested
Fixes # (ME-2653)
Tested with local build.
> fix(ME-2653): don't use login cmd if no pty is requested

- cmd/client/rdp/rdp.go
- internal/connector_v2/upstreamdata/rdp.go
- internal/connector_v2/upstreamdata/top_level.go
- internal/enum/socket_types.go
Adds rdp sockets support to connector v2
-  https://mysocket.atlassian.net/browse/ME-2656
Tested locally...
[ME-2656]: https://mysocket.atlassian.net/browse/ME-2656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2656] RDP Socket Support in Connector V2

- cmd/client.go
- cmd/client/tcp/tcp.go
- internal/connector_v2/upstreamdata/tcp.go
- internal/connector_v2/upstreamdata/top_level.go
Adds support for "tcp" sockets and backwards compatibility with TLS sockets (e.g. TLS sockets will show up under tcp command)
- https://mysocket.atlassian.net/browse/ME-2652
Locally... note I can still list tls sockets with the tcp command
```
12:11 $ ./border0 client tcp
? choose a host:  [Use arrows to move, type to filter]
> word-server-olympus.border0.io []
kali-vnc-olympus.border0.io []
adrianos-laptop-vnc-olympus.border0.io []
echo-olympus.border0.io [Authenticated TCP socket playground with Border0 sandbox server.]
purple-cake-olympus.border0.io []
```
and can still list tls sockets with tls command
```
12:11 $ ./border0 client tls
? choose a host:  [Use arrows to move, type to filter]
> word-server-olympus.border0.io []
kali-vnc-olympus.border0.io [] …
```
> [ME-2652] Add support for tcp sockets

- internal/ssh/server/server.go
- internal/ssh/server/server_unix.go
- internal/ssh/session/local_session.go
fix command execution with pty for connector built-in ssh server (ansible fix)
Fixes # (ME-2654)
Tested with:
* Ansible
* ansible without ControlMaster
* ansible with pipelining
* echo "ls -l" | ssh -tt ..
*  ssh -tt .. ls -l
*  ssh -tt .. wrongcommand
*  ssh with normal session
> fix(ME-2654): fix command execution with pty for connector built-in ssh server (ansible fix)

- cmd/client/vpn/vpn.go
- internal/api/models/socket.go
- internal/border0/socket.go
- internal/connector_v2/service.go
- internal/connector_v2/upstreamdata/vpn.go
- internal/enum/socket_types.go
- internal/vpnlib/vpnlib.go
VPN sockets in the connector.
- https://mysocket.atlassian.net/browse/ME-2657
It has been tested in MacOS and Debian
https://github.com/borderzero/border0-cli/assets/16856511/8ec572b0-ca0f-4dd9-9097-ae2dda97a335
> Note that the token in the video above is revoked ;) 
[ME-2657]: https://mysocket.atlassian.net/browse/ME-2657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2657] Run VPN Server as Connector Socket

- cmd/client/rdp/rdp.go
- cmd/client/utils/local_proxy_and_client.go
- cmd/client/vnc/vnc.go
- internal/client/client.go
Reported by internal QA:
```
✘-1 ~/go/src/github.com/borderzero/border0-cli [ME-2681_vnc_panic_fix|✔]
08:04 $ border0 client vnc
? choose a host: kali-real-vnc-olympus.border0.io []
2024/03/13 08:04:47 Waiting for connections on localhost:63708...
failed to connect: failed to authenticate to connector: EOF
2024/03/13 08:04:48 Connection established from 127.0.0.1:63709
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1028d1248]
goroutine 16 [running]:
crypto/tls.(*Conn).Close(0x108468220?)
/opt/hostedtoolcache/go/1.22.0/x64/src/crypto/tls/conn.go:1404 +0x18
github.com/borderzero/border0-cli/cmd/client/utils.copyStream.func1.1()
/home/runner/work/border0-cli/border0-cli/cmd/client/utils/copy.go:27 +0x54 …
```
> [ME-2681] Fix Panic on RDP/VNC Unauthorized

- cmd/client.go
- cmd/client/db/datagrip.go
- cmd/client/db/db.go
- cmd/client/db/dbeaver.go
- cmd/client/db/mycli.go
- cmd/client/db/mysql.go
- cmd/client/db/mysql_workbench.go
- cmd/client/db/pgcli.go
- cmd/client/db/psql.go
- cmd/client/db/sqlcmd.go
- cmd/client/db/ssms.go
- cmd/client/httpproxy/httpproxy.go
- cmd/client/rdp/rdp.go
- cmd/client/ssh/ssh.go
- cmd/client/tcp/tcp.go
- cmd/client/utils/local_proxy_and_client.go
- cmd/client/vnc/vnc.go
- cmd/client/vpn/vpn.go
- internal/client/client.go
- internal/client/sqlclientproxy/mysql.go
- internal/client/sqlclientproxy/postgres.go
- internal/client/sqlclientproxy/proxy.go
- internal/client/sqlclientproxy/tcp.go
add wsproxy support for all client commands
Fixes # (ME-2680)
Tested with database, ssh, tls, proxy sockets. Some with e2ee disabled and enabled.
Not tested with VNC, RDP or VPN sockets, but those are built on top of tls.
> feat(ME-2680): add wsproxy support for all client commands

- internal/sqlauthproxy/handler.go
- internal/ssh/proxy.go
Respect context cancellation in socket connection acceptance.
This addresses a goroutine leak bug which was aggravated recently by adding context cancellations.
- https://mysocket.atlassian.net/browse/ME-2685
Tested on MacOS and Debian.
[ME-2685]: https://mysocket.atlassian.net/browse/ME-2685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2685] Fix Infinite Connection Accept in SSH/SQL Proxies

- internal/border0/socket.go
Giving the base socket object the same treatment as SQL + SSH. See https://github.com/borderzero/border0-cli/pull/327 for more detail.
The bug did not exist here.. but this change basically just makes an unnecessary error message go away:
```
{"level":"error","ts":"2024-03-13T22:08:53-07:00","msg":"proxy failed","socket_id":"37c774ba-b1ab-4d5c-b492-172ece20319e","socket":"37c774ba-b1ab-4d5c-b492-172ece20319e","error":"failed to accept connection: context canceled"}
```
[ME-2685]: https://mysocket.atlassian.net/browse/ME-2685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2685] Graceful Socket Exit on Context Cancellation

- cmd/connector.go
- internal/api/api.go
- internal/api/models/connector.go
- internal/connector_v2/config/config.go
- internal/connector_v2/invite/invite.go
- internal/files/files.go
add new flag `--invite` to `border0 connector start` to support automatically creating connector and connector token from an invite code, and then use the returned connector token to start the connector process.
Tested locally with:
```shell
make build-all -j # build for all platforms in parallel
docker buildx build --platform linux/arm64 -t border0:test .
docker run -ti border0:test connector start --invite <invite_code>
```
> ME-2674: support `--invite` in connector start command

- internal/connector_v2/service.go
- internal/vpnlib/server.go
Including more log types in the existing log suppression mechanism for VPN server related logs.
- https://mysocket.atlassian.net/browse/ME-2692
Tested on MacOS and Debian VPN servers
[ME-2692]: https://mysocket.atlassian.net/browse/ME-2692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2692] Verbose Logs Option for VPN

- cmd/client/vpn/vpn.go
- cmd/socket.go
- internal/vpnlib/server.go
Bail if VPN client, socket connect vpn, or connector with vpn socket is not running as system administrator.
- https://mysocket.atlassian.net/browse/ME-2691
Tested in MacOS and Debian
Testing bail when connector not root
```
┌──(scr1pt3r㉿pwnbox)-[~/go/src/github.com/borderzero/border0-cli]
└─$ ./border0 connector start
{"level":"info","ts":"2024-03-14T16:16:25-07:00","msg":"using config file in the service config directory","config_path":"/etc/border0/border0.yaml"}
{"level":"info","ts":"2024-03-14T16:16:25-07:00","msg":"reading the config","config_path":"/etc/border0/border0.yaml"}
{"level":"info","ts":"2024-03-14T16:16:25-07:00","msg":"starting the connector service"}
{"level":"info","ts":"2024-03-14T16:16:25-07:00","msg":"connecting to connector …
```
> [ME-2691] VPN: Bail On No Sudo

- cmd/client/ssh/ssh.go
- cmd/client/utils/local_proxy_and_client.go
- internal/client/client.go
NPE:
```
$ border0 client rdp
? choose a host: shy-breeze-border0-demo.border0.io []
2024/03/18 13:09:17 Waiting for connections on localhost:61070...
failed to connect: failed to authenticate against connector: EOF
2024/03/18 13:09:17 Connection established from 127.0.0.1:61071
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x104f2b498]
goroutine 23 [running]:
github.com/borderzero/border0-cli/cmd/client/utils.copyStream.func1()
/home/runner/work/border0-cli/border0-cli/cmd/client/utils/copy.go:41 +0xc8
created by github.com/borderzero/border0-cli/cmd/client/utils.copyStream in goroutine 70
/home/runner/work/border0-cli/border0-cli/cmd/client/utils/copy.go:24 +0xe0
```
- …
> [ME-2711] Fix NPE in Client TLS/VNC/RDP

- cmd/client/utils/local_proxy_and_client.go
Some VNC clients set up two connections, one to authenticate and one to actually stream.... So we can't kill the local listener after one connection. 
We also have no way of knowing if your VNC server will request auth or not, nor if your client does two separate conns or not... so we can't have this change.
[ME-2711]: https://mysocket.atlassian.net/browse/ME-2711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert "[ME-2711] Exit Local Listener After One Fail"

- cmd/connector.go
- internal/connector_v2/install/aws.go
- internal/connector_v2/invite/invite.go
Extends the AWS connector installer to allow for invite codes.
- https://mysocket.atlassian.net/browse/ME-2727
Tested locally
[ME-2727]: https://mysocket.atlassian.net/browse/ME-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2727] Extend AWS Connector Installer to Use Invite Codes

- cmd/connector.go
- internal/connector_v2/install/aws.go
- internal/connector_v2/install/local.go
Connector install options for the web-based AWS installer to persist/retrieve tokens for invite codes from AWS SSM.
- https://mysocket.atlassian.net/browse/ME-2727
N/A
[ME-2727]: https://mysocket.atlassian.net/browse/ME-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2727] Token Persistence for Connector Install

- cmd/client.go
- cmd/whoami.go
- internal/api/api.go
- internal/client/client.go
- internal/client/resources.go
Adds support for service account tokens. Service account tokens have a long lifetime, potentially infinite. If the token itself doesnt have an `exp` claim then we won't ask the user to log in as long as it also has a `service_account_id` claim.
(Obviously there is server side logic to handle this in terms of authentication, what we are changing here is just the client side logic to determine if the user should be prompted to log in or not).
- https://mysocket.atlassian.net/browse/ME-2710
This has been tested using service identity tokens as client tokens and admin tokens. Also tested with human auth and legacy token auth.
[ME-2710]: https://mysocket.atlassian.net/browse/ME-2710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2710] Support for Service Account Tokens

- cmd/serviceaccount/cmd_serviceaccount_token_create.go
- cmd/serviceaccount/cmd_serviceaccount_update.go
- cmd/serviceaccount/common.go
- cmd/serviceaccount/root_serviceaccount.go
- cmd/serviceaccount/root_serviceaccounttoken.go
- https://mysocket.atlassian.net/browse/ME-2770
Tested with the locally built version of the CLI:
```
✔ ~/go/src/github.com/borderzero/border0-cli [ME-2770_add_update_svc_account|✔]
12:44 $ ./border0 organization service-account list
+--------------------------+--------+--------+-------------+----------------------+----------------------+
| NAME                     | ROLE   | ACTIVE | DESCRIPTION | CREATED AT           | UPDATED AT           |
+--------------------------+--------+--------+-------------+----------------------+----------------------+
| adrianos-service-account | client | true   | whatever    | 2024-04-02T18:14:56Z | 2024-04-02T19:30:40Z | …
```
> [ME-2770] Support for Update Service Account

- .github/workflows/build_and_release.yml
We need to trigger AWX-EE build after border0 release to keep the public facing software in sync
N/A - trigger for external repo build
> ME-2777: trigger AWX-EE build after border0 release

- internal/vpnlib/iputil.go
- internal/vpnlib/vpnlib.go
Updating vpn socket MTU 
```
root@au-rpi0w:/home/pi# ip -s -d link sho dev tun0
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1380 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 500
link/none  promiscuity 0  allmulti 0 minmtu 68 maxmtu 65535 
tun type tun pi off vnet_hdr off persist off addrgenmode random numtxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536 
RX:  bytes packets errors dropped  missed   mcast           
372886    1743      0       0       0       0 
TX:  bytes packets errors dropped carrier collsns           
437512    2105      0       0       0       0 
root@au-rpi0w:/home/pi# tcpdump  -ln -i tun0 icmp -c 2
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on …
```
> ME-2781 RFC2460: VPN socket MTU
